const RINCHAN_V129='v0.9.29';
function v129Esc(v){return String(v||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function v129Num(n){return Number(n||0).toLocaleString('ja-JP')}
function v129Date(v){const d=v?new Date(v):new Date();if(isNaN(d))return '-';return (d.getMonth()+1)+'/'+d.getDate()+' '+String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0')}
async function v129Api(action,payload){if(typeof v051Api==='function')return v051Api(action,payload||{});if(typeof rinchanApi==='function')return rinchanApi(action,payload||{});return{ok:false,reason:'api_not_ready'}}
let V129_DATA=null;
document.addEventListener('DOMContentLoaded',()=>{v129Load();const r=document.getElementById('adminRefresh');if(r)r.addEventListener('click',v129Load);const q=document.getElementById('adminSearch');if(q)q.addEventListener('input',()=>v129RenderMembers(V129_DATA));});
async function v129Load(){const status=document.getElementById('adminStatus');if(status)status.textContent='読み込み中...';const result=await v129Api('adminStats',{});if(!result||!result.ok){if(status)status.textContent='取得できません：'+v129Esc((result&&(result.reason||result.error))||'unknown');v129RenderEmpty();return;}V129_DATA=result.data||{};if(status)status.textContent='更新 '+v129Date(V129_DATA.generatedAt);v129Render(V129_DATA)}
function v129Render(data){v129Text('adminTotalUsers',v129Num(data.totalUsers)+'人');v129Text('adminTotalActivities',v129Num(data.totalActivities)+'回');v129Text('adminTotalSteps',v129Num(data.totalSteps)+'歩');v129Text('adminDeptCount',v129Num((data.departments||[]).length)+'部署');v129RenderDepartments(data);v129RenderDeptRanking(data);v129RenderMembers(data);v129RenderUnset(data)}
function v129Text(id,text){const el=document.getElementById(id);if(el)el.textContent=text}
function v129RenderEmpty(){['adminDepartments','adminDeptRanking','adminMembers','adminUnsetMembers'].forEach(id=>{const el=document.getElementById(id);if(el)el.innerHTML='<p class="admin-empty">データを取得できません。</p>'})}
function v129RenderDepartments(data){const box=document.getElementById('adminDepartments');if(!box)return;const list=(data.departments||[]).slice().sort((a,b)=>Number(a.displayOrder||999)-Number(b.displayOrder||999));if(!list.length){box.innerHTML='<p class="admin-empty">所属マスターがありません。</p>';return;}box.innerHTML='<div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>順番</th><th>所属名</th><th>deptId</th><th>mapKey</th><th>表示</th></tr></thead><tbody>'+list.map(d=>'<tr><td>'+v129Num(d.displayOrder)+'</td><td><strong>'+v129Esc(d.deptName)+'</strong></td><td>'+v129Esc(d.deptId)+'</td><td>'+v129Esc(d.mapKey)+'</td><td><span class="admin-pill '+(d.active?'on':'off')+'">'+(d.active?'表示':'非表示')+'</span></td></tr>').join('')+'</tbody></table></div>'}
function v129RenderDeptRanking(data){const box=document.getElementById('adminDeptRanking');if(!box)return;const list=(data.deptRanking||[]).slice().sort((a,b)=>Number(b.totalSteps||0)-Number(a.totalSteps||0));if(!list.length){box.innerHTML='<p class="admin-empty">部署別データはまだありません。</p>';return;}box.innerHTML='<div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>順位</th><th>所属</th><th>人数</th><th>記録</th><th>歩数</th></tr></thead><tbody>'+list.map((d,i)=>'<tr><td class="admin-rank">#'+(i+1)+'</td><td><strong>'+v129Esc(d.dept||'所属未設定')+'</strong></td><td>'+v129Num(d.userCount)+'人</td><td>'+v129Num(d.activityCount)+'回</td><td>'+v129Num(d.totalSteps)+'歩</td></tr>').join('')+'</tbody></table></div>'}
function v129RenderMembers(data){const box=document.getElementById('adminMembers');if(!box)return;const q=String((document.getElementById('adminSearch')||{}).value||'').trim().toLowerCase();let rows=(data.csvRows||[]).reduce((map,r)=>{const id=String(r.participantId||'');if(!id)return map;if(!map[id])map[id]={participantId:id,name:r.name||'',nick:r.nick||'',dept:r.dept||'',activityCount:0,totalSteps:0,lastDate:''};map[id].activityCount+=1;map[id].totalSteps+=Number(r.steps||0);if(!map[id].lastDate||String(r.date||'')>map[id].lastDate)map[id].lastDate=String(r.date||'');return map;},{});let list=Object.values(rows).sort((a,b)=>Number(b.totalSteps||0)-Number(a.totalSteps||0));if(q)list=list.filter(m=>(m.name+' '+m.nick+' '+m.dept+' '+m.participantId).toLowerCase().includes(q));if(!list.length){box.innerHTML='<p class="admin-empty">該当する利用者がありません。</p>';return;}box.innerHTML='<div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>氏名</th><th>所属</th><th>記録</th><th>歩数</th><th>最終日</th></tr></thead><tbody>'+list.map(m=>'<tr><td><strong>'+v129Esc(m.name||m.nick||'ゲスト')+'</strong></td><td>'+v129Esc(m.dept||'所属未設定')+'</td><td>'+v129Num(m.activityCount)+'回</td><td>'+v129Num(m.totalSteps)+'歩</td><td>'+v129Esc(m.lastDate||'-')+'</td></tr>').join('')+'</tbody></table></div>'}
function v129RenderUnset(data){const box=document.getElementById('adminUnsetMembers');if(!box)return;const ids={};(data.csvRows||[]).forEach(r=>{const id=String(r.participantId||'');if(!id)return;if(!ids[id])ids[id]={participantId:id,name:r.name||'',dept:r.dept||'',count:0};ids[id].count++;});const list=Object.values(ids).filter(m=>!String(m.dept||'').trim()||String(m.dept)==='所属未設定').sort((a,b)=>b.count-a.count);if(!list.length){box.innerHTML='<p class="admin-empty">所属未設定の記録者はいません。</p>';return;}box.innerHTML='<div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>氏名</th><th>状態</th><th>記録</th></tr></thead><tbody>'+list.map(m=>'<tr><td><strong>'+v129Esc(m.name||'ゲスト')+'</strong></td><td><span class="admin-pill off">所属未設定</span></td><td>'+v129Num(m.count)+'回</td></tr>').join('')+'</tbody></table></div>'}
