const RINCHAN_V129='v0.9.31';
function v129Esc(v){return String(v||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function v129Num(n){return Number(n||0).toLocaleString('ja-JP')}
function v129Date(v){const d=v?new Date(v):new Date();if(isNaN(d))return '-';return (d.getMonth()+1)+'/'+d.getDate()+' '+String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0')}
function v129Participant(){try{return JSON.parse(localStorage.getItem('rinchanParticipant')||'null')}catch(e){return null}}
async function v129Api(action,payload){if(typeof v051Api==='function')return v051Api(action,payload||{});if(typeof rinchanApi==='function')return rinchanApi(action,payload||{});return{ok:false,reason:'api_not_ready'}}
let V129_DATA=null;
document.addEventListener('DOMContentLoaded',()=>{const p=v129Participant();if(!p||String(p.admin||'')!=='1'){document.getElementById('adminStatus').textContent='管理者権限がありません。users シートの admin 列に 1 が必要です。';v129RenderBlocked();return;}v129Load();const r=document.getElementById('adminRefresh');if(r)r.addEventListener('click',v129Load);const q=document.getElementById('adminSearch');if(q)q.addEventListener('input',()=>v129RenderMembers(V129_DATA));});
function v129RenderBlocked(){['adminOperations','adminDeptRanking','adminInactiveMembers','adminMembers'].forEach(id=>{const el=document.getElementById(id);if(el)el.innerHTML='<p class="admin-empty">管理者のみ表示できます。</p>'})}
async function v129Load(){const status=document.getElementById('adminStatus');if(status)status.textContent='読み込み中...';const p=v129Participant()||{};const result=await v129Api('adminStats',{employeeId:p.employeeId||p.id});if(!result||!result.ok){if(status)status.textContent='取得できません：'+v129Esc((result&&(result.reason||result.error))||'unknown');v129RenderEmpty();return;}V129_DATA=result.data||{};if(status)status.textContent='更新 '+v129Date(V129_DATA.generatedAt);v129Render(V129_DATA)}
function v129Render(data){v129Text('adminTotalUsers',v129Num(data.totalUsers)+'人');v129Text('adminTodayUsers',v129Num(data.todayUsers)+'人');v129Text('adminTodayActivities',v129Num(data.todayActivities)+'回');v129Text('adminTodaySteps',v129Num(data.todaySteps)+'歩');v129RenderOperations(data);v129RenderDeptRanking(data);v129RenderInactive(data);v129RenderMembers(data)}
function v129Text(id,text){const el=document.getElementById(id);if(el)el.textContent=text}
function v129RenderEmpty(){['adminOperations','adminDeptRanking','adminInactiveMembers','adminMembers'].forEach(id=>{const el=document.getElementById(id);if(el)el.innerHTML='<p class="admin-empty">データを取得できません。</p>'})}
function v129RenderOperations(data){const box=document.getElementById('adminOperations');if(!box)return;const unset=data.unsetMembers||[];const inactive=data.inactiveMembers||[];const rows=[{label:'所属未設定',value:unset.length+'人',state:unset.length?'off':'on',note:unset.length?'マイページで所属変更が必要です':'問題ありません'},{label:'7日以上記録なし',value:inactive.length+'人',state:inactive.length?'off':'on',note:inactive.length?'声かけ候補です':'問題ありません'},{label:'本日の記録者',value:(data.todayUsers||0)+'人',state:(data.todayUsers||0)?'on':'off',note:'今日歩数を登録した人数'},{label:'有効所属数',value:(data.departments||[]).length+'部署',state:'on',note:'departments シート active=TRUE'}];box.innerHTML='<div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>項目</th><th>状況</th><th>メモ</th></tr></thead><tbody>'+rows.map(r=>'<tr><td><strong>'+v129Esc(r.label)+'</strong></td><td><span class="admin-pill '+r.state+'">'+v129Esc(r.value)+'</span></td><td>'+v129Esc(r.note)+'</td></tr>').join('')+'</tbody></table></div>'}
function v129RenderDeptRanking(data){const box=document.getElementById('adminDeptRanking');if(!box)return;const list=(data.deptRanking||[]).slice().sort((a,b)=>Number(b.last7Steps||0)-Number(a.last7Steps||0)||Number(b.todaySteps||0)-Number(a.todaySteps||0));if(!list.length){box.innerHTML='<p class="admin-empty">部署別データはまだありません。</p>';return;}box.innerHTML='<div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>所属</th><th>7日歩数</th><th>7日記録</th><th>今日</th><th>累計</th></tr></thead><tbody>'+list.map(d=>'<tr><td><strong>'+v129Esc(d.dept||'所属未設定')+'</strong><br><small>'+v129Num(d.userCount)+'人</small></td><td>'+v129Num(d.last7Steps)+'歩</td><td>'+v129Num(d.last7Count)+'回</td><td>'+v129Num(d.todaySteps)+'歩 / '+v129Num(d.todayCount)+'回</td><td>'+v129Num(d.totalSteps)+'歩</td></tr>').join('')+'</tbody></table></div>'}
function v129RenderInactive(data){const box=document.getElementById('adminInactiveMembers');if(!box)return;const list=(data.inactiveMembers||[]).slice(0,50);if(!list.length){box.innerHTML='<p class="admin-empty">7日以上記録がない人はいません。</p>';return;}box.innerHTML='<div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>氏名</th><th>所属</th><th>最終記録</th><th>累計</th></tr></thead><tbody>'+list.map(m=>'<tr><td><strong>'+v129Esc(m.name||m.nick||'ゲスト')+'</strong></td><td>'+v129Esc(m.dept||'所属未設定')+'</td><td>'+v129Esc(m.lastDate||'記録なし')+'</td><td>'+v129Num(m.totalSteps)+'歩 / '+v129Num(m.activityCount)+'回</td></tr>').join('')+'</tbody></table></div>'}
function v129RenderMembers(data){const box=document.getElementById('adminMembers');if(!box||!data)return;const q=String((document.getElementById('adminSearch')||{}).value||'').trim().toLowerCase();let list=(data.users||[]).slice().sort((a,b)=>Number(b.totalSteps||0)-Number(a.totalSteps||0));if(q)list=list.filter(m=>(m.name+' '+m.nick+' '+m.dept+' '+m.employeeId).toLowerCase().includes(q));if(!list.length){box.innerHTML='<p class="admin-empty">該当する利用者がありません。</p>';return;}box.innerHTML='<div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>氏名</th><th>所属</th><th>記録</th><th>歩数</th><th>最終日</th></tr></thead><tbody>'+list.map(m=>'<tr><td><strong>'+v129Esc(m.name||m.nick||'ゲスト')+'</strong>'+(String(m.admin||'')==='1'?' <span class="admin-pill on">管理</span>':'')+'</td><td>'+v129Esc(m.dept||'所属未設定')+'</td><td>'+v129Num(m.activityCount)+'回</td><td>'+v129Num(m.totalSteps)+'歩</td><td>'+v129Esc(m.lastDate||'-')+'</td></tr>').join('')+'</tbody></table></div>'}
