const RINCHAN_V135_SYNC='v0.9.53';
function v135ReadJson(key,fallback){try{const r=localStorage.getItem(key);return r?JSON.parse(r):fallback}catch(e){return fallback}}
function v135SaveJson(key,value){localStorage.setItem(key,JSON.stringify(value))}
function v135Participant(){return v135ReadJson('rinchanParticipant',null)}
function v135SaveParticipant(p){localStorage.setItem('rinchanParticipant',JSON.stringify(p))}
function v135EmployeeId(){const p=v135Participant();return p&&(p.employeeId||p.id)?String(p.employeeId||p.id):''}
async function v135Api(action,payload){if(typeof v051Api==='function')return v051Api(action,payload||{});return{ok:false,reason:'api_not_ready'}}
function v135NormalizeActivities(list){return(Array.isArray(list)?list:[]).map(a=>({activityId:String(a.activityId||''),participantId:String(a.participantId||a.id||''),deviceId:String(a.deviceId||''),date:String(a.date||'').slice(0,10),steps:Number(a.steps||0),challenge:a.challenge===true||String(a.challenge).toUpperCase()==='TRUE',comment:String(a.comment||''),createdAt:String(a.createdAt||a.date||''),version:String(a.version||RINCHAN_V135_SYNC),savedAt:String(a.savedAt||'')})).filter(a=>a.activityId||a.date||a.steps>0)}
function v135NormalizeThanks(list){return(Array.isArray(list)?list:[]).map(t=>Object.assign({},t,{thanksId:String(t.thanksId||t.id||''),createdAt:String(t.createdAt||''),reason:String(t.reason||'ありがとう')}))}
function v135ApplyState(state){if(!state)return;if(state.user){const current=v135Participant()||{};v135SaveParticipant(Object.assign({},current,state.user));}if(Array.isArray(state.activities)){v135SaveJson('rinchanActivities',v135NormalizeActivities(state.activities));}if(Array.isArray(state.receivedThanks)){v135SaveJson('rinchanReceivedThanks',v135NormalizeThanks(state.receivedThanks));}if(Array.isArray(state.sentThanks)){v135SaveJson('rinchanSentThanks',v135NormalizeThanks(state.sentThanks));}if(Array.isArray(state.thanksTimeline)){v135SaveJson('rinchanGoodTimeline',state.thanksTimeline);}if(Array.isArray(state.readNewsIds)){v135SaveJson('rinchanReadNewsIds',state.readNewsIds);}if(state.thanksStats){v135SaveJson('rinchanThanksStats',state.thanksStats);}}
async function v135SyncUserState(){const employeeId=v135EmployeeId();if(!employeeId)return;const res=await v135Api('getUserState',{employeeId});if(!res||!res.ok||!res.state)return;v135ApplyState(res.state);v135RefreshUi();}
function v135RefreshUi(){try{if(typeof renderV078Chart==='function')renderV078Chart();}catch(e){}try{if(typeof renderV070Mypage==='function')renderV070Mypage();}catch(e){}try{if(typeof v136RenderGoal==='function')v136RenderGoal();}catch(e){}try{if(typeof v113LoadReceivedThanks==='function')v113LoadReceivedThanks();}catch(e){}try{if(typeof v100RenderSummary==='function')v100RenderSummary();}catch(e){}try{if(typeof v100RenderThanksFlowSummary==='function')v100RenderThanksFlowSummary();}catch(e){}try{if(typeof v100RenderThanksStories==='function')v100RenderThanksStories();}catch(e){}try{if(typeof v100RenderGroupNews==='function')v100RenderGroupNews();}catch(e){}try{if(typeof updateNewsBadgesV051==='function')updateNewsBadgesV051();}catch(e){}try{if(typeof updateNewsRowsV051==='function')updateNewsRowsV051();}catch(e){}try{if(typeof v100RenderNotices==='function')v100RenderNotices();}catch(e){}try{if(typeof renderAdminButtonV131==='function')renderAdminButtonV131();}catch(e){}}
async function v135MarkNewsRead(newsId){const employeeId=v135EmployeeId();if(!employeeId||!newsId)return;const res=await v135Api('markNewsRead',{employeeId,newsId});if(res&&res.ok&&res.state){v135ApplyState(res.state);v135RefreshUi();}}
(function(){const oldMark=window.markNoticeReadV113;window.markNoticeReadV113=function(id){if(typeof oldMark==='function')oldMark(id);v135MarkNewsRead(id);};const oldOpen=window.openNews;window.openNews=function(id){if(typeof oldOpen==='function')oldOpen(id);v135MarkNewsRead(id);};document.addEventListener('DOMContentLoaded',()=>{v135SyncUserState();});})();