const RinchanSync = (() => {
  const VERSION = 'v1.4.8';
  const SYNC_TIME_KEY = 'rinchanLastSyncedAt';
  const SYNC_STATUS_KEY = 'rinchanSyncStatus';
  const SYNC_TOKEN_KEY = 'rinchanSyncToken';

  function readJson(key, fallback) { if (typeof RinchanStorage !== 'undefined' && RinchanStorage && typeof RinchanStorage.readJson === 'function') return RinchanStorage.readJson(key, fallback); try { const raw = localStorage.getItem(key); return raw ? JSON.parse(raw) : fallback; } catch (e) { return fallback; } }
  function writeJson(key, value) { if (typeof RinchanStorage !== 'undefined' && RinchanStorage && typeof RinchanStorage.writeJson === 'function') return RinchanStorage.writeJson(key, value); localStorage.setItem(key, JSON.stringify(value)); return value; }
  function participant() { if (typeof RinchanStorage !== 'undefined' && RinchanStorage && typeof RinchanStorage.getParticipant === 'function') return RinchanStorage.getParticipant(); return readJson('rinchanParticipant', null); }
  function safeUser(user) { if (!user || typeof user !== 'object') return user; const safe = Object.assign({}, user); delete safe.pin4; delete safe.pin; delete safe.password; return safe; }
  function employeeId() { if (typeof RinchanStorage !== 'undefined' && RinchanStorage && typeof RinchanStorage.employeeId === 'function') return RinchanStorage.employeeId(); const user = participant(); return user && (user.employeeId || user.id) ? String(user.employeeId || user.id) : ''; }
  function syncToken() { return String(localStorage.getItem(SYNC_TOKEN_KEY) || '').trim(); }
  function saveSyncToken(token) { if (token) localStorage.setItem(SYNC_TOKEN_KEY, String(token)); }
  function uniq(list) { return Array.from(new Set((list || []).map(String).filter(Boolean))); }
  function mergeIds(localKey, incoming) { return uniq([].concat(readJson(localKey, []), incoming || [])); }
  function mergeUserReads(state) {
    const current = readJson('rinchanUserReads', {});
    const server = state && state.userReads && typeof state.userReads === 'object' ? state.userReads : {};
    const readNewsIds = uniq([].concat(readJson('rinchanReadNewsIds', []), current.readNewsIds || [], state.readNewsIds || [], server.readNewsIds || []));
    const readThanksFlowerIds = uniq([].concat(readJson('rinchanReadThanksFlowerIds', []), current.readThanksFlowerIds || [], state.readThanksFlowerIds || [], server.readThanksFlowerIds || []));
    writeJson('rinchanReadNewsIds', readNewsIds);
    writeJson('rinchanReadThanksFlowerIds', readThanksFlowerIds);
    writeJson('rinchanUserReads', Object.assign({}, current, server, { readNewsIds, readThanksFlowerIds, updatedAt: new Date().toISOString() }));
  }
  function dateKeyFromDate(date) { return date.getFullYear() + '-' + String(date.getMonth() + 1).padStart(2, '0') + '-' + String(date.getDate()).padStart(2, '0'); }
  function normalizeDateKey(value) { const raw = String(value || '').trim(); const iso = raw.match(/^(\d{4})[-/](\d{1,2})[-/](\d{1,2})/); if (iso) return iso[1] + '-' + String(iso[2]).padStart(2, '0') + '-' + String(iso[3]).padStart(2, '0'); const parsed = new Date(raw); if (!isNaN(parsed)) return dateKeyFromDate(parsed); return raw.slice(0, 10); }
  function newerScore(item) { const saved = Date.parse(item.savedAt || ''); const created = Date.parse(item.createdAt || ''); return Math.max(isNaN(saved) ? 0 : saved, isNaN(created) ? 0 : created); }
  function normalizeActivities(list) { const normalized = (Array.isArray(list) ? list : []).map(item => ({ activityId: String(item.activityId || ''), participantId: String(item.participantId || item.employeeId || item.id || ''), employeeId: String(item.employeeId || item.participantId || item.id || ''), id: String(item.id || item.employeeId || item.participantId || ''), deviceId: String(item.deviceId || ''), date: normalizeDateKey(item.date || item.createdAt || item.savedAt), steps: Number(item.steps || 0), challenge: item.challenge === true || String(item.challenge).toUpperCase() === 'TRUE', comment: String(item.comment || ''), createdAt: String(item.createdAt || item.savedAt || item.date || ''), version: String(item.version || VERSION), savedAt: String(item.savedAt || '') })).filter(item => item.activityId || item.date || item.steps > 0); const byDate = {}; normalized.forEach(item => { const key = normalizeDateKey(item.date); if (!key) return; const ownerKey = item.participantId ? item.participantId + '|' + key : key; const current = byDate[ownerKey]; if (!current || newerScore(item) >= newerScore(current)) byDate[ownerKey] = Object.assign({}, item, { date: key }); }); return Object.values(byDate).sort((a, b) => normalizeDateKey(b.date).localeCompare(normalizeDateKey(a.date)) || newerScore(b) - newerScore(a)); }
  function normalizeThanks(list) { return (Array.isArray(list) ? list : []).map(item => Object.assign({}, item, { thanksId: String(item.thanksId || item.id || ''), createdAt: String(item.createdAt || item.savedAt || ''), reason: String(item.reason || item.message || 'ありがとう') })); }
  function normalizeMembers(list) { return (Array.isArray(list) ? list : []).map(item => ({ employeeId: String(item.employeeId || item.id || item.participantId || ''), id: String(item.id || item.employeeId || item.participantId || ''), name: String(item.name || item.displayName || ''), nick: String(item.nick || item.nickname || ''), dept: String(item.dept || item.department || item.section || 'その他'), totalSteps: Number(item.totalSteps || item.steps || item.sumSteps || 0), activityCount: Number(item.activityCount || item.count || 0) })).filter(item => item.employeeId || item.id || item.name || item.dept); }
  function normalizeDepartments(list) { return (Array.isArray(list) ? list : []).map(item => typeof item === 'string' ? { id: item, name: item } : { id: String(item.id || item.name || item.dept || item.department || ''), name: String(item.name || item.dept || item.department || item.id || '') }).filter(item => item.name); }

  function applyState(state) { if (!state) return false; if (state.syncToken) saveSyncToken(state.syncToken); if (state.unchanged === true) { mergeUserReads(state); return false; } if (state.user) { const current = participant() || {}; writeJson('rinchanParticipant', Object.assign({}, safeUser(current), safeUser(state.user))); } if (Array.isArray(state.activities)) writeJson('rinchanActivities', normalizeActivities(state.activities)); if (Array.isArray(state.allActivities)) writeJson('rinchanAllActivities', normalizeActivities(state.allActivities)); if (Array.isArray(state.receivedThanks)) writeJson('rinchanReceivedThanks', normalizeThanks(state.receivedThanks)); if (Array.isArray(state.sentThanks)) writeJson('rinchanSentThanks', normalizeThanks(state.sentThanks)); if (Array.isArray(state.thanksTimeline)) writeJson('rinchanGoodTimeline', normalizeThanks(state.thanksTimeline)); if (Array.isArray(state.challenges)) writeJson('rinchanChallenges', state.challenges); if (Array.isArray(state.badges)) writeJson('rinchanBadgeConfigs', state.badges); if (Array.isArray(state.events)) writeJson('rinchanEventConfigs', state.events); mergeUserReads(state); if (state.thanksStats) writeJson('rinchanThanksStats', state.thanksStats); if (state.forestSummary || state.summary) writeJson('rinchanForestSummary', state.forestSummary || state.summary); const members = state.moriMembers || state.members || state.users || state.participants || state.allUsers; if (Array.isArray(members)) writeJson('rinchanMoriMembers', normalizeMembers(members)); const departments = state.departments || state.depts || state.sections; if (Array.isArray(departments)) writeJson('rinchanDepartments', normalizeDepartments(departments)); if (state.mori || state.forest) writeJson('rinchanMoriState', state.mori || state.forest); return true; }
  function setStatus(status, message) { const now = new Date().toISOString(); writeJson(SYNC_STATUS_KEY, { status, message: message || '', at: now }); if (status === 'synced') localStorage.setItem(SYNC_TIME_KEY, now); renderStatus(); }
  function formatSyncTime(value) { if (!value) return '未同期'; const date = new Date(value); if (isNaN(date)) return '未同期'; return (date.getMonth() + 1) + '/' + date.getDate() + ' ' + String(date.getHours()).padStart(2, '0') + ':' + String(date.getMinutes()).padStart(2, '0'); }
  function renderStatus() { const page = document.querySelector('.app'); if (!page) return; let box = document.getElementById('rinchanSyncStatus'); if (!box) { box = document.createElement('div'); box.id = 'rinchanSyncStatus'; box.className = 'rinchan-sync-status'; const nav = page.querySelector('.nav'); if (nav) page.insertBefore(box, nav); else page.appendChild(box); } const status = readJson(SYNC_STATUS_KEY, null); const lastSync = localStorage.getItem(SYNC_TIME_KEY); const label = status && status.status === 'syncing' ? '同期中...' : '最終同期 ' + formatSyncTime(lastSync); const detail = status && status.status === 'error' ? '通信できませんでした。保存済みデータを表示中です。' : ''; box.innerHTML = '<span>' + label + '</span>' + (detail ? '<small>' + detail + '</small>' : ''); box.classList.toggle('is-syncing', !!status && status.status === 'syncing'); box.classList.toggle('is-error', !!status && status.status === 'error'); }
  function refreshUi() { try { if (typeof renderV078Chart === 'function') renderV078Chart(); } catch (e) {} try { if (typeof renderV070Mypage === 'function') renderV070Mypage(); } catch (e) {} try { if (window.RinchanMypage && typeof RinchanMypage.renderAll === 'function') RinchanMypage.renderAll(); } catch (e) {} try { if (window.RinchanPassportRender && typeof RinchanPassportRender.render === 'function') RinchanPassportRender.render(); } catch (e) {} try { if (typeof v100RenderSummary === 'function') v100RenderSummary(); } catch (e) {} try { if (typeof v100RenderThanksFlowSummary === 'function') v100RenderThanksFlowSummary(); } catch (e) {} try { if (typeof v100RenderGroupNews === 'function') v100RenderGroupNews(); } catch (e) {} try { if (typeof updateNewsBadgesV051 === 'function') updateNewsBadgesV051(); } catch (e) {} try { if (typeof updateNewsRowsV051 === 'function') updateNewsRowsV051(); } catch (e) {} try { if (typeof v100RenderNotices === 'function') v100RenderNotices(); } catch (e) {} try { if (window.RinchanNews && typeof RinchanNews.renderAll === 'function') RinchanNews.renderAll(); } catch (e) {} try { if (window.RinchanNews && typeof RinchanNews.updateBadges === 'function') RinchanNews.updateBadges(); } catch (e) {} try { if (window.RinchanThanksHomeNotice && typeof RinchanThanksHomeNotice.render === 'function') RinchanThanksHomeNotice.render(); } catch (e) {} try { if (window.RinchanMori && typeof RinchanMori.renderAll === 'function') RinchanMori.renderAll(); } catch (e) {} try { if (window.RinchanEventCalendarEngine && typeof RinchanEventCalendarEngine.install === 'function') RinchanEventCalendarEngine.install(); } catch (e) {} try { if (window.RinchanEventLoader && typeof RinchanEventLoader.install === 'function') RinchanEventLoader.install(); } catch (e) {} try { if (window.RinchanEventHighlightLock && typeof RinchanEventHighlightLock.install === 'function') RinchanEventHighlightLock.install(); } catch (e) {} try { if (window.RinchanMonthlyChallengeRender) RinchanMonthlyChallengeRender.render(); } catch (e) {} try { if (window.RinchanDepartmentChallengeRender) RinchanDepartmentChallengeRender.render(); } catch (e) {} try { if (window.RinchanHospitalChallengeRender) RinchanHospitalChallengeRender.render(); } catch (e) {} renderStatus(); }
  async function request(action, payload) { if (typeof RinchanApi !== 'undefined' && RinchanApi && typeof RinchanApi.request === 'function') return RinchanApi.request(action, payload || {}); if (window.RinchanApi && typeof window.RinchanApi.request === 'function') return window.RinchanApi.request(action, payload || {}); if (typeof v051Api === 'function') return v051Api(action, payload || {}); return { ok: false, reason: 'api_not_ready' }; }
  async function sync(options) { const id = employeeId(); if (!id) { renderStatus(); return; } const silent = options && options.silent === true; if (!silent) setStatus('syncing', ''); try { const payload = { employeeId: id }; const token = syncToken(); if (token) payload.syncToken = token; const response = await request('getUserState', payload); if (!response || !response.ok || !response.state) throw new Error('sync_failed'); const changed = applyState(response.state); setStatus('synced', changed ? '' : 'unchanged'); refreshUi(); } catch (e) { setStatus('error', e.message || 'sync_failed'); refreshUi(); } }
  function applyApiResult(response) { if (!response || !response.ok || !response.state) return response; applyState(response.state); setStatus('synced', ''); refreshUi(); return response; }
  return { VERSION, sync, applyState, applyApiResult, refreshUi, renderStatus, setStatus, syncToken };
})();
window.RinchanSync = RinchanSync;
