const RinchanMori = (() => {
  const VERSION = 'v1.0.21';
  const SENT_KEY = 'rinchanThanksSentTargets';
  const THANKS_REASONS = ['ありがとう', '助けてもらった', '声をかけてもらった', '一緒にがんばった'];

  function readJson(key, fallback) { if (window.RinchanStorage && typeof RinchanStorage.readJson === 'function') return RinchanStorage.readJson(key, fallback); try { const raw = localStorage.getItem(key); return raw ? JSON.parse(raw) : fallback; } catch (e) { return fallback; } }
  function writeJson(key, value) { if (window.RinchanStorage && typeof RinchanStorage.writeJson === 'function') return RinchanStorage.writeJson(key, value); localStorage.setItem(key, JSON.stringify(value)); return value; }
  async function api(action, payload) { if (window.RinchanApi && typeof RinchanApi.request === 'function') return RinchanApi.request(action, payload || {}); if (typeof v051Api === 'function') return v051Api(action, payload || {}); return { ok: false, reason: 'api_not_ready' }; }
  function participant() { if (window.RinchanStorage && typeof RinchanStorage.getParticipant === 'function') return RinchanStorage.getParticipant(); return readJson('rinchanParticipant', null); }
  function deviceId() { if (window.RinchanStorage && typeof RinchanStorage.deviceId === 'function') return RinchanStorage.deviceId(); return localStorage.getItem('rinchanDeviceId') || ''; }
  function activities() { const all = readJson('rinchanAllActivities', []); return Array.isArray(all) && all.length ? all : readJson('rinchanActivities', []); }
  function normalizeDeptName(value) { return String(value || '').trim() || 'その他'; }
  function normalizeMember(item) { return { employeeId: String(item.employeeId || item.id || item.participantId || ''), id: String(item.id || item.employeeId || item.participantId || ''), name: String(item.name || item.displayName || ''), nick: String(item.nick || item.nickname || ''), dept: normalizeDeptName(item.dept || item.department || item.section), totalSteps: Number(item.totalSteps || item.steps || item.sumSteps || 0), activityCount: Number(item.activityCount || item.count || 0) }; }
  function members() { const list = readJson('rinchanMoriMembers', []); if (Array.isArray(list) && list.length) return list.map(normalizeMember); const byUser = {}; activities().forEach(item => { const id = String(item.participantId || item.employeeId || item.id || ''); if (!id) return; if (!byUser[id]) byUser[id] = { employeeId: id, id, name: '', nick: '', dept: normalizeDeptName(item.dept || item.department || item.section), totalSteps: 0, activityCount: 0 }; byUser[id].totalSteps += Number(item.steps || 0); byUser[id].activityCount += 1; }); const rows = Object.values(byUser); if (rows.length) return rows; const user = participant(); if (user && (user.employeeId || user.id)) return [{ employeeId: user.employeeId || user.id, id: user.id || user.employeeId, name: user.name || user.nick || '', nick: user.nick || '', dept: normalizeDeptName(user.dept || user.department), totalSteps: readJson('rinchanActivities', []).reduce((sum, item) => sum + Number(item.steps || 0), 0), activityCount: readJson('rinchanActivities', []).length }]; return []; }
  function departments() { const cached = readJson('rinchanDepartments', []); const rows = Array.isArray(cached) && cached.length ? cached.map(dept => typeof dept === 'string' ? { id: dept, name: dept } : { id: String(dept.id || dept.name || dept.dept || dept.department || ''), name: normalizeDeptName(dept.name || dept.dept || dept.department || dept.id) }).filter(dept => dept.name) : []; const names = Array.from(new Set(members().map(member => normalizeDeptName(member.dept)))).filter(Boolean); names.forEach(name => { if (!rows.some(row => normalizeDeptName(row.name) === name)) rows.push({ id: name, name }); }); if (rows.length) return rows; return [{ id: 'nurse', name: '看護部' }, { id: 'reha', name: 'リハビリテーション部' }, { id: 'care', name: '介護部' }, { id: 'doctor', name: '医局' }, { id: 'pharmacy', name: '薬剤部' }, { id: 'nutrition', name: '栄養科' }, { id: 'office', name: '事務部' }, { id: 'other', name: 'その他' }]; }
  function totalSteps() { const mori = readJson('rinchanMoriState', null); if (mori && Number(mori.totalSteps || mori.steps) > 0) return Number(mori.totalSteps || mori.steps); const memberList = members(); if (memberList.length) return memberList.reduce((sum, item) => sum + Number(item.totalSteps || item.steps || 0), 0); return activities().reduce((sum, item) => sum + Number(item.steps || 0), 0); }
  function moriLevel(steps) { const thresholds = [0, 10000, 50000, 100000, 250000, 500000, 1000000, 2000000]; let level = 1; for (let i = 0; i < thresholds.length; i += 1) if (steps >= thresholds[i]) level = i + 1; const next = thresholds[level] || thresholds[thresholds.length - 1]; const prev = thresholds[level - 1] || 0; const progress = next > prev ? Math.min(100, Math.round(((steps - prev) / (next - prev)) * 100)) : 100; return { level, next, prev, progress }; }
  function iconForLevel(level) { if (level >= 7) return '🌲'; if (level >= 5) return '🌳'; if (level >= 3) return '🌿'; return '🌱'; }
  function seasonMessage() { const hour = new Date().getHours(); if (hour < 10) return '朝の杜に、今日の一歩が集まりはじめました。'; if (hour < 16) return '今日の杜の様子を表示しています。'; return '一日の歩みで、杜がゆっくり育っています。'; }
  function renderStatus() { const steps = totalSteps(); const level = moriLevel(steps); const icon = document.getElementById('moriStatusIcon'); const levelEl = document.getElementById('moriStatusLevel'); const stepsEl = document.getElementById('moriStatusSteps'); const bar = document.getElementById('moriStatusProgressBar'); const note = document.getElementById('moriStatusProgressNote'); const season = document.getElementById('moriSeasonMessage'); const updated = document.getElementById('moriUpdatedAt'); if (icon) icon.textContent = iconForLevel(level.level); if (levelEl) levelEl.textContent = '杜レベル ' + level.level; if (stepsEl) stepsEl.textContent = '累計 ' + steps.toLocaleString() + '歩'; if (bar) bar.style.width = level.progress + '%'; if (note) { const remain = Math.max(0, level.next - steps); note.textContent = remain > 0 ? 'あと' + remain.toLocaleString() + '歩でレベル ' + (level.level + 1) : '最高レベルに到達しました'; } if (season) season.textContent = seasonMessage(); if (updated) updated.textContent = '最終更新 ' + formatTime(new Date()); }
  function groupByDept() { const deptMap = {}; departments().forEach(dept => { const name = normalizeDeptName(dept.name || dept.dept || dept.id); deptMap[name] = { dept: name, steps: 0, members: 0 }; }); members().forEach(member => { const dept = normalizeDeptName(member.dept); if (!deptMap[dept]) deptMap[dept] = { dept, steps: 0, members: 0 }; deptMap[dept].members += 1; deptMap[dept].steps += Number(member.totalSteps || member.steps || 0); }); return Object.keys(deptMap).map(key => deptMap[key]).sort((a, b) => Number(b.steps || 0) - Number(a.steps || 0) || String(a.dept).localeCompare(String(b.dept))); }
  function membersByDept(deptName) { return members().filter(member => normalizeDeptName(member.dept) === normalizeDeptName(deptName)); }
  function hasSentTo(id) { return !!readJson(SENT_KEY, {})[String(id || '')]; }
  function markSentTo(id) { const map = readJson(SENT_KEY, {}); if (id) map[String(id)] = new Date().toISOString(); writeJson(SENT_KEY, map); }
  function isSelfMember(member) { const current = participant() || {}; const currentId = String(current.employeeId || current.id || '').trim(); const memberId = String(member.employeeId || member.id || '').trim(); if (currentId && memberId && currentId === memberId) return true; const currentNames = [current.nick, current.name].map(v => String(v || '').trim()).filter(Boolean); const memberNames = [member.nick, member.name].map(v => String(v || '').trim()).filter(Boolean); return currentNames.some(name => memberNames.includes(name)); }
  function renderMap() { const map = document.getElementById('moriMap'); if (!map) return; const rows = groupByDept(); if (!rows.length) { map.innerHTML = '<p class="empty-note">杜を読み込み中です。</p>'; return; } map.innerHTML = rows.map(row => { const level = moriLevel(Number(row.steps || 0)); return '<button type="button" class="dept-node mori-tree-node" onclick="RinchanMori.showDept(\'' + escapeAttr(row.dept) + '\')"><span>' + iconForLevel(level.level) + '</span><strong>' + escapeHtml(row.dept) + '</strong><em>' + Number(row.members || 0).toLocaleString() + '人</em><small>' + Number(row.steps || 0).toLocaleString() + '歩</small></button>'; }).join(''); }
  function memberAction(member, name, id) { if (isSelfMember(member)) return '<span class="dept-self-label">自分</span>'; if (hasSentTo(id)) return '<span class="dept-sent-label">送信済み</span>'; return '<button type="button" class="dept-member-thanks" onclick="RinchanMori.openThanksPicker(\'' + escapeAttr(id) + '\',\'' + escapeAttr(name) + '\')">ありがとう</button>'; }
  function showDept(deptName) { const card = document.getElementById('treeInfoCard'); if (!card) return; const row = groupByDept().find(item => normalizeDeptName(item.dept) === normalizeDeptName(deptName)) || { dept: deptName, steps: 0, members: 0 }; const level = moriLevel(Number(row.steps || 0)); const deptMembers = membersByDept(deptName); const memberHtml = deptMembers.length ? '<div class="dept-member-list">' + deptMembers.map(member => { const id = String(member.employeeId || member.id || ''); const name = member.nick || member.name || 'メンバー'; const steps = Number(member.totalSteps || member.steps || 0).toLocaleString(); return '<div class="dept-member-item" data-member-id="' + escapeAttr(id) + '"><div><strong>' + escapeHtml(name) + '</strong><small>' + steps + '歩</small></div>' + memberAction(member, name, id) + '</div>'; }).join('') + '</div>' : '<p class="dept-empty-note">この部署には、まだ登録メンバーがいません。</p>'; card.classList.remove('hidden'); card.innerHTML = '<button type="button" class="tree-card-close" onclick="RinchanMori.hideDept()">×</button><p class="label">部署の木</p><h2 class="dept-card-title">' + escapeHtml(row.dept) + '</h2><div class="tree-card-icon dept-icon">' + iconForLevel(level.level) + '</div><div class="mini-stats"><div><strong>' + Number(row.steps || 0).toLocaleString() + '歩</strong><small>累計歩数</small></div><div><strong>' + Number(row.members || 0).toLocaleString() + '人</strong><small>登録メンバー</small></div><div><strong>Lv.' + level.level + '</strong><small>成長</small></div></div><p class="dept-note">どんなありがとうを送るか選べます。</p>' + memberHtml; card.scrollIntoView({ behavior: 'smooth', block: 'nearest' }); }
  function toast(message, type) { let box = document.getElementById('rinchanBusyToast'); if (!box) { box = document.createElement('div'); box.id = 'rinchanBusyToast'; document.body.appendChild(box); } box.className = 'rinchan-busy-toast' + (type ? ' ' + type : ''); box.textContent = message; return box; }
  function hideToast(delay) { const box = document.getElementById('rinchanBusyToast'); if (!box) return; setTimeout(() => { if (box.parentNode) box.parentNode.removeChild(box); }, delay || 900); }
  function failureText(result) { if (!result) return '応答なし'; const raw = result.raw && (result.raw.error || result.raw.reason) ? ' / raw:' + (result.raw.error || result.raw.reason) : ''; return String(result.error || result.reason || 'api_error') + raw; }
  function closeThanksPicker() { const box = document.getElementById('thanksReasonSheet'); if (box && box.parentNode) box.parentNode.removeChild(box); }
  function openThanksPicker(toId, toName) { if (!toId || hasSentTo(toId)) return; const target = members().find(member => String(member.employeeId || member.id || '') === String(toId)); if (target && isSelfMember(target)) return; closeThanksPicker(); const sheet = document.createElement('div'); sheet.id = 'thanksReasonSheet'; sheet.className = 'thanks-reason-sheet'; sheet.innerHTML = '<div class="thanks-reason-backdrop" onclick="RinchanMori.closeThanksPicker()"></div><div class="thanks-reason-panel"><button type="button" class="thanks-reason-close" onclick="RinchanMori.closeThanksPicker()">×</button><p class="label">💌 ありがとう</p><h2>' + escapeHtml(toName || '仲間') + 'さんへ</h2><p class="thanks-reason-help">どんなありがとうを届けますか？</p><div class="thanks-reason-options">' + THANKS_REASONS.map(reason => '<button type="button" onclick="RinchanMori.sendThanks(\'' + escapeAttr(toId) + '\',\'' + escapeAttr(toName || '') + '\',\'' + escapeAttr(reason) + '\')">' + escapeHtml(reason) + '</button>').join('') + '</div></div>'; document.body.appendChild(sheet); }
  function updateLocalAfterThanks(payload, target) { const current = participant() || {}; const fromDept = normalizeDeptName(current.dept || '杜の仲間'); const toDept = normalizeDeptName((target && target.dept) || payload.toDept || '杜の仲間'); const reason = payload.reason || 'ありがとう'; const detail = reason && reason !== 'ありがとう' ? '「' + reason + '」のありがとうを届けました。' : 'ありがとうを届けました。'; const publicItem = { id: payload.thanksId, thanksId: payload.thanksId, icon: '❤️', title: 'ありがとうが届けられました', body: fromDept + 'の仲間が、' + toDept + 'の仲間に' + detail, publicBody: fromDept + 'の仲間が、' + toDept + 'の仲間に' + detail, fromDept, toDept, targetDept: toDept, reason, createdAt: payload.createdAt }; const timeline = readJson('rinchanGoodTimeline', []).filter(item => String(item.thanksId || item.id || '') !== payload.thanksId); timeline.unshift(publicItem); writeJson('rinchanGoodTimeline', timeline.slice(0, 50)); const sent = readJson('rinchanSentThanks', []).filter(item => String(item.thanksId || item.id || '') !== payload.thanksId); sent.unshift(payload); writeJson('rinchanSentThanks', sent.slice(0, 50)); const received = readJson('rinchanReceivedThanks', []); writeJson('rinchanThanksStats', { sentCount: sent.length, receivedCount: received.length, totalCount: sent.length + received.length }); }
  function setButtonSent(button, toId) { markSentTo(toId); if (!button) return; const row = button.closest('.dept-member-item'); if (row) { const holder = document.createElement('span'); holder.className = 'dept-sent-label'; holder.textContent = '送信済み'; button.replaceWith(holder); } else { button.disabled = true; button.classList.remove('is-loading'); button.classList.add('is-sent'); button.textContent = '送信済み'; } }
  async function sendThanks(toId, toName, reason) { closeThanksPicker(); if (!toId || hasSentTo(toId)) return; const target = members().find(member => String(member.employeeId || member.id || '') === String(toId)); if (target && isSelfMember(target)) return; const current = participant() || {}; const fromId = current.employeeId || current.id || ''; if (!fromId) { toast('ログイン情報を確認してください', 'is-error'); hideToast(1600); return; } const name = toName || (target && (target.nick || target.name)) || 'メンバー'; const button = document.querySelector('.dept-member-item[data-member-id="' + cssEscape(String(toId)) + '"] .dept-member-thanks'); if (button) { button.disabled = true; button.classList.add('is-loading'); button.textContent = '送信中...'; } toast(name + 'さんへ送信中...'); const payload = { thanksId: 'K' + Date.now().toString(36) + Math.random().toString(36).slice(2, 7), fromParticipantId: fromId, fromName: current.nick || current.name || '杜の仲間', toParticipantId: toId, toName: name, toDept: target ? target.dept : '', reason: reason || 'ありがとう', createdAt: new Date().toISOString(), deviceId: deviceId(), version: VERSION }; const result = await api('saveThanks', payload); if (result && result.ok) { if (window.RinchanSync && typeof RinchanSync.applyApiResult === 'function') RinchanSync.applyApiResult(result); updateLocalAfterThanks(payload, target); setButtonSent(button, toId); toast('ありがとうを送りました', 'is-done'); hideToast(1200); if (window.RinchanNews && typeof RinchanNews.renderAll === 'function') RinchanNews.renderAll(); if (window.RinchanMypage && typeof RinchanMypage.renderAll === 'function') RinchanMypage.renderAll(); setTimeout(() => refresh(), 500); return; } toast('送信できませんでした', 'is-error'); hideToast(2200); alert('送信できませんでした。\n原因: ' + failureText(result)); if (button) { button.disabled = false; button.classList.remove('is-loading'); button.textContent = 'ありがとう'; } }
  function hideDept() { const card = document.getElementById('treeInfoCard'); if (card) { card.classList.add('hidden'); card.innerHTML = ''; } }
  function renderHighlight() { const title = document.getElementById('moriHighlightTitle'); const text = document.getElementById('moriHighlightText'); const rows = groupByDept().slice().sort((a, b) => Number(b.steps || 0) - Number(a.steps || 0)); if (!rows.length) return; const top = rows[0]; if (title) title.textContent = '今日の杜'; if (text) text.textContent = top.dept + 'の木がよく育っています。みんなの一歩で杜全体が広がります。'; }
  function renderAll() { renderStatus(); renderMap(); renderHighlight(); }
  async function fetchGlobalState() { const id = (participant() && (participant().employeeId || participant().id)) || ''; const res = await api('getUserState', { employeeId: id, forceGlobal: true }); if (res && res.ok && res.state) { if (window.RinchanSync && typeof RinchanSync.applyState === 'function') RinchanSync.applyState(res.state); return true; } return false; }
  async function refresh() { if (window.RinchanSync && typeof RinchanSync.sync === 'function') await RinchanSync.sync({ silent: true }); await fetchGlobalState(); renderAll(); }
  function install() { renderAll(); refresh(); const refreshButton = document.getElementById('refreshMoriButton'); if (refreshButton && !refreshButton.__rinchanMoriInstalled) { refreshButton.__rinchanMoriInstalled = true; refreshButton.addEventListener('click', refresh); } window.renderMoriMapV071 = renderMap; window.renderMoriStatusV144 = renderStatus; }
  function formatTime(date) { return (date.getMonth() + 1) + '/' + date.getDate() + ' ' + String(date.getHours()).padStart(2, '0') + ':' + String(date.getMinutes()).padStart(2, '0'); }
  function escapeHtml(value) { return String(value || '').replace(/[&<>'"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c])); }
  function escapeAttr(value) { return escapeHtml(value).replace(/`/g, '&#96;'); }
  function cssEscape(value) { if (window.CSS && typeof CSS.escape === 'function') return CSS.escape(value); return String(value).replace(/[^a-zA-Z0-9_-]/g, '\\$&'); }
  document.addEventListener('DOMContentLoaded', install);
  return { VERSION, install, renderAll, renderStatus, renderMap, renderHighlight, refresh, showDept, hideDept, openThanksPicker, closeThanksPicker, sendThanks };
})();
