const RinchanMypage = (() => {
  const VERSION = 'v1.0.31';
  const RECENT_ACTIVITY_LIMIT = 3;
  const THANKS_RECORD_LIMIT = 5;

  function readJson(key, fallback) { if (window.RinchanStorage && typeof RinchanStorage.readJson === 'function') return RinchanStorage.readJson(key, fallback); try { const raw = localStorage.getItem(key); return raw ? JSON.parse(raw) : fallback; } catch (e) { return fallback; } }
  function writeJson(key, value) { if (window.RinchanStorage && typeof RinchanStorage.writeJson === 'function') return RinchanStorage.writeJson(key, value); localStorage.setItem(key, JSON.stringify(value)); return value; }
  function participant() { if (window.RinchanStorage && typeof RinchanStorage.getParticipant === 'function') return RinchanStorage.getParticipant(); return readJson('rinchanParticipant', null); }
  function isRegistered(user) { return !!(user && (user.employeeId || user.id)); }
  function dateKeyFromDate(date) { return date.getFullYear() + '-' + String(date.getMonth() + 1).padStart(2, '0') + '-' + String(date.getDate()).padStart(2, '0'); }
  function normalizeDateKey(value) { const raw = String(value || '').trim(); const iso = raw.match(/^(\d{4})[-/](\d{1,2})[-/](\d{1,2})/); if (iso) return iso[1] + '-' + String(iso[2]).padStart(2, '0') + '-' + String(iso[3]).padStart(2, '0'); const parsed = new Date(raw); if (!isNaN(parsed)) return dateKeyFromDate(parsed); return raw.slice(0, 10); }
  function formatDateLabel(value) { const key = normalizeDateKey(value); const parts = key.split('-'); if (parts.length !== 3) return key.replace(/-/g, '/'); const y = Number(parts[0]); const m = Number(parts[1]); const d = Number(parts[2]); if (!y || !m || !d) return key.replace(/-/g, '/'); const dt = new Date(y, m - 1, d); const days = ['日', '月', '火', '水', '木', '金', '土']; return String(m).padStart(2, '0') + '/' + String(d).padStart(2, '0') + ' ' + days[dt.getDay()]; }
  function newerScore(item) { const saved = Date.parse(item.savedAt || ''); const created = Date.parse(item.createdAt || ''); return Math.max(isNaN(saved) ? 0 : saved, isNaN(created) ? 0 : created); }
  function normalizedActivities() { const byDate = {}; (readJson('rinchanActivities', []) || []).forEach(item => { const key = normalizeDateKey(item.date || item.createdAt || item.savedAt); if (!key) return; const row = { activityId: String(item.activityId || ''), date: key, steps: Number(item.steps || 0), challenge: item.challenge === true || String(item.challenge).toUpperCase() === 'TRUE', comment: String(item.comment || ''), createdAt: String(item.createdAt || item.savedAt || item.date || ''), savedAt: String(item.savedAt || '') }; const current = byDate[key]; if (!current || newerScore(row) >= newerScore(current)) byDate[key] = row; }); const rows = Object.values(byDate).sort((a, b) => normalizeDateKey(b.date).localeCompare(normalizeDateKey(a.date)) || newerScore(b) - newerScore(a)); writeJson('rinchanActivities', rows); return rows; }
  function activities() { return normalizedActivities(); }
  function sentThanks() { return readJson('rinchanSentThanks', []); }
  function receivedThanks() { return readJson('rinchanReceivedThanks', []); }
  function thanksStats() { const stored = readJson('rinchanThanksStats', null); const sent = sentThanks().length; const received = receivedThanks().length; if (stored && (Number(stored.sentCount || 0) || Number(stored.receivedCount || 0) || Number(stored.totalCount || 0))) return stored; return { sentCount: sent, receivedCount: received, totalCount: sent + received }; }
  function setText(id, value) { const el = document.getElementById(id); if (el) el.textContent = value; }
  function totalSteps() { return activities().reduce((sum, item) => sum + Number(item.steps || 0), 0); }
  function activityDays() { return Array.from(new Set(activities().map(item => normalizeDateKey(item.date)).filter(Boolean))).sort(); }
  function treeState(steps) { if (steps >= 300000) return { icon: '🌲', title: '大きな杜の木になりました', text: 'たくさんの歩みが、しっかりした木を育てています。', progress: 100 }; if (steps >= 100000) return { icon: '🌳', title: '木が大きく育っています', text: '日々の記録が、あなたの木を育てています。', progress: 80 }; if (steps >= 30000) return { icon: '🌿', title: '若葉が広がっています', text: '少しずつ、あなたの木に葉が増えています。', progress: 55 }; if (steps >= 5000) return { icon: '🌱', title: '芽が育ちはじめました', text: '今日の一歩が、次の成長につながります。', progress: 30 }; return { icon: '🌱', title: '小さな芽が出ました', text: '活動を記録すると、あなたの木が育ちます。', progress: 10 }; }
  function streak() { const days = activityDays(); if (!days.length) return { current: 0, best: 0 }; const set = new Set(days); const today = new Date(); let current = 0; for (let i = 0; i < 365; i += 1) { const d = new Date(today); d.setDate(today.getDate() - i); if (set.has(dateKeyFromDate(d))) current += 1; else if (i > 0) break; } let best = 1; let run = 1; for (let i = 1; i < days.length; i += 1) { const prev = new Date(days[i - 1]); const cur = new Date(days[i]); const diff = Math.round((cur - prev) / 86400000); if (diff === 1) run += 1; else run = 1; best = Math.max(best, run); } return { current, best }; }
  function renderProfile() { const user = participant() || {}; setText('v070ProfileName', user.name || 'ゲスト'); setText('v070ProfileDept', user.dept || '未設定'); setText('v070EmployeeId', user.employeeId || user.id || '-'); setText('v070ProfileNick', user.nick || '-'); setText('weeklyGoalText', user.weeklyGoal || '未設定'); setText('declarationText', user.declaration || 'まだ登録されていません。'); setText('v136WeeklyStepGoalText', user.weeklyStepGoal ? Number(user.weeklyStepGoal).toLocaleString() + '歩' : '未設定'); setText('dailyStepGoalText', user.dailyStepGoal ? Number(user.dailyStepGoal).toLocaleString() + '歩' : '未設定'); const note=document.getElementById('dailyStepGoalNote'); if(note) note.textContent=user.dailyStepGoal?'達成すると日次目標達成Hの対象になります。':'目標を設定すると、達成時に5H獲得できます。'; }
  function renderTree() { const state = treeState(totalSteps()); setText('treeIcon', state.icon); setText('treeTitle', state.title); setText('treeText', state.text); setText('growthNote', state.progress >= 100 ? 'しっかり育っています。' : '次の成長まで、あと少し。'); const bar = document.getElementById('growthBar'); if (bar) bar.style.width = state.progress + '%'; }
  function renderActivityStats() { const rows = activities(); const createdAt = participant() && participant().createdAt ? new Date(participant().createdAt) : new Date(); const age = Math.max(1, Math.ceil((new Date() - createdAt) / 86400000) + 1); const s = streak(); setText('v070TreeAge', age.toLocaleString() + '日'); setText('v070TotalSteps', totalSteps().toLocaleString() + '歩'); setText('v070ActivityCount', rows.length.toLocaleString() + '回'); setText('v070Streak', s.current.toLocaleString() + '日'); setText('v070BestStreak', s.best.toLocaleString() + '日'); }
  function renderHistory() { const box = document.getElementById('v070History'); if (!box) return; const rows = activities().slice(0, RECENT_ACTIVITY_LIMIT); if (!rows.length) { box.innerHTML = '<p class="empty-note">まだ記録がありません。</p>'; return; } box.innerHTML = rows.map(item => { const comment = String(item.comment || '').trim(); return '<div class="history-row"><div class="history-row-main"><span class="history-row-date">' + escapeHtml(formatDateLabel(item.date)) + '</span><strong class="history-row-steps">' + Number(item.steps || 0).toLocaleString() + '歩</strong></div>' + (comment ? '<small>' + escapeHtml(comment) + '</small>' : '') + '</div>'; }).join('') + '<p class="list-limit-note">最近' + RECENT_ACTIVITY_LIMIT + '件を表示しています。</p>'; }
  function renderThanksStats() { const s = thanksStats(); setText('v139SentThanksCount', Number(s.sentCount || 0).toLocaleString() + '件'); setText('v139ReceivedThanksCount', Number(s.receivedCount || 0).toLocaleString() + '件'); setText('v139TotalThanksCount', Number(s.totalCount || 0).toLocaleString() + '件'); }
  function formatThanksDate(value) { const d = new Date(value || ''); if (isNaN(d)) return ''; return (d.getMonth() + 1) + '/' + d.getDate() + ' ' + String(d.getHours()).padStart(2, '0') + ':' + String(d.getMinutes()).padStart(2, '0'); }
  function renderReceivedList() { const box = document.getElementById('receivedThanksList'); if (!box) return; const rows = receivedThanks().map(item => Object.assign({ direction: '受信' }, item)).concat(sentThanks().map(item => Object.assign({ direction: '送信' }, item))).sort((a, b) => String(b.createdAt || '').localeCompare(String(a.createdAt || ''))).slice(0, THANKS_RECORD_LIMIT); if (!rows.length) { box.innerHTML = '<p class="received-thanks-empty">まだありがとうの記録はありません。</p>'; return; } box.innerHTML = rows.map(item => { const isSent = item.direction === '送信'; const target = isSent ? (item.toName || item.toDept || '仲間') + 'さんへ' : (item.fromName || '杜の仲間') + 'さんから'; const reason = item.reason || 'ありがとう'; return '<div class="received-thanks-row thanks-record-row ' + (isSent ? 'is-sent-record' : 'is-received-record') + '"><div class="thanks-record-line thanks-record-head"><span class="thanks-record-pill">' + escapeHtml(item.direction) + '</span><strong>' + escapeHtml(target) + '</strong></div><div class="thanks-record-line thanks-record-body"><span>' + escapeHtml(reason) + '</span><time>' + escapeHtml(formatThanksDate(item.createdAt)) + '</time></div></div>'; }).join('') + '<p class="list-limit-note">最近' + THANKS_RECORD_LIMIT + '件を表示しています。</p>'; }
  function badgeTheme(type, earned) { if (!earned) return { start:'#dfe6e1', end:'#cfd8d2', ring:'#e8eeea', ribbon:'#c4cec7' }; const themes = { steps:{ start:'#67c7df', end:'#75c96b', ring:'#d9f4e4', ribbon:'#72c17c' }, thanks:{ start:'#f6a6b8', end:'#f3c1d1', ring:'#fae6ed', ribbon:'#eb95af' }, forest:{ start:'#8fd171', end:'#56b67e', ring:'#def4de', ribbon:'#5db77b' }, streak:{ start:'#f7c35f', end:'#f49e49', ring:'#fff0c9', ribbon:'#f0a54b' }, special:{ start:'#95a7ff', end:'#7fd5e8', ring:'#e3e9ff', ribbon:'#8aa0f5' } }; return themes[type] || themes.forest; }
  function badgeSvg(badge, index) { const t = badgeTheme(badge.type, badge.earned); const gid = 'badgeGrad' + index + (badge.earned ? 'On' : 'Off'); return '<svg class="rinchan-medal-svg" viewBox="0 0 100 110" aria-hidden="true"><defs><linearGradient id="' + gid + '" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="' + t.start + '"/><stop offset="100%" stop-color="' + t.end + '"/></linearGradient></defs><path d="M34 72 L25 101 L42 90 L50 104 L58 90 L75 101 L66 72 Z" fill="' + t.ribbon + '" opacity=".96"></path><circle cx="50" cy="43" r="34" fill="' + t.ring + '" opacity=".98"></circle><circle cx="50" cy="43" r="27" fill="url(#' + gid + ')"></circle><circle cx="50" cy="43" r="35" fill="none" stroke="rgba(36,64,56,.12)" stroke-width="2"></circle><ellipse cx="42" cy="30" rx="13" ry="7" fill="#fff" opacity=".25"></ellipse><text x="50" y="53" text-anchor="middle" class="badge-core-icon">' + escapeHtml(badge.icon) + '</text><text x="50" y="86" text-anchor="middle" class="badge-ribbon-text">RIN</text></svg>'; }
  function lockSvg() { return '<span class="rinchan-medal-lock" aria-label="未獲得"><svg viewBox="0 0 24 24" fill="none"><path d="M8 10V7.8C8 5.7 9.8 4 12 4C14.2 4 16 5.7 16 7.8V10" stroke="#6E8077" stroke-width="2" stroke-linecap="round"/><rect x="6" y="10" width="12" height="10" rx="3" fill="#EFF4EF" stroke="#6E8077" stroke-width="2"/><circle cx="12" cy="15" r="1.5" fill="#6E8077"/></svg></span>'; }
  function renderBadges() { const box = document.getElementById('badgeList'); if (!box) return; const steps = totalSteps(); const count = activities().length; const thanks = thanksStats().totalCount || 0; const badges = [{ type:'steps', icon:'👟', title:'はじめの一歩', note:'最初の活動記録', earned:count >= 1 }, { type:'streak', icon:'🏅', title:'継続の芽', note:'7回記録', earned:count >= 7 }, { type:'forest', icon:'🌿', title:'若葉バッジ', note:'30,000歩達成', earned:steps >= 30000 }, { type:'forest', icon:'🌳', title:'成長の木', note:'100,000歩達成', earned:steps >= 100000 }, { type:'thanks', icon:'💌', title:'ありがとう', note:'ありがとう参加', earned:thanks >= 1 }, { type:'special', icon:'🏆', title:'杜の達人', note:'300,000歩達成', earned:steps >= 300000 }]; box.innerHTML = badges.map((badge, index) => '<div class="badge-card premium-badge rinchan-medal-badge ' + (badge.earned ? 'is-earned' : 'is-locked') + '"><div class="rinchan-medal-wrap">' + badgeSvg(badge, index) + (badge.earned ? '' : lockSvg()) + '</div><strong class="rinchan-badge-title">' + escapeHtml(badge.title) + '</strong><small class="rinchan-badge-note">' + escapeHtml(badge.note) + '</small></div>').join(''); }
  function hideEdit() { document.querySelectorAll('.form.edit-panel').forEach(el => el.classList.add('hidden')); document.body.classList.remove('edit-open'); }
  function showEdit(id) { const user = participant(); if (!isRegistered(user)) { alert('登録後に編集できます。'); location.href = 'login.html'; return; } hideEdit(); if (id === 'profileEdit') { setInput('editName', user.name || ''); setInput('editDept', user.dept || ''); setInput('editNick', user.nick || ''); } if (id === 'declarationEdit') setInput('editDeclaration', user.declaration || ''); if (id === 'goalEdit') setInput('editGoal', user.weeklyGoal || ''); if (id === 'weeklyStepGoalEdit') setInput('editWeeklyStepGoal', user.weeklyStepGoal || ''); if (id === 'dailyStepGoalEdit') setInput('editDailyStepGoal', user.dailyStepGoal || ''); const box = document.getElementById(id); if (box) { if (box.parentElement !== document.body) document.body.appendChild(box); box.classList.remove('hidden'); document.body.classList.add('edit-open'); } }
  function setInput(id, value) { const el = document.getElementById(id); if (el) el.value = value; }
  function renderAll() { renderProfile(); renderTree(); renderActivityStats(); renderHistory(); renderThanksStats(); renderReceivedList(); renderBadges(); }
  function install() { if (!document.getElementById('mypageV070')) return; renderAll(); window.renderV070Mypage = renderAll; window.showEdit = showEdit; window.hideEdit = hideEdit; }
  function escapeHtml(value) { return String(value || '').replace(/[&<>'"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c])); }
  document.addEventListener('DOMContentLoaded', install); window.showEdit = showEdit; window.hideEdit = hideEdit;
  return { VERSION, install, renderAll, renderProfile, renderTree, renderHistory, renderBadges, renderReceivedList, showEdit, hideEdit };
})();
window.RinchanMypage = RinchanMypage;
