const RinchanNews = (() => {
  const VERSION = 'v1.0.31';

  function readJson(key, fallback) { if (window.RinchanStorage && typeof RinchanStorage.readJson === 'function') return RinchanStorage.readJson(key, fallback); try { const raw = localStorage.getItem(key); return raw ? JSON.parse(raw) : fallback; } catch (e) { return fallback; } }
  function writeJson(key, value) { if (window.RinchanStorage && typeof RinchanStorage.writeJson === 'function') return RinchanStorage.writeJson(key, value); localStorage.setItem(key, JSON.stringify(value)); return value; }
  function participant() { if (window.RinchanStorage && typeof RinchanStorage.getParticipant === 'function') return RinchanStorage.getParticipant(); return readJson('rinchanParticipant', null); }
  function employeeId() { const user = participant(); return user && (user.employeeId || user.id) ? String(user.employeeId || user.id) : ''; }
  async function api(action, payload) { if (window.RinchanApi && typeof RinchanApi.request === 'function') return RinchanApi.request(action, payload || {}); if (typeof v051Api === 'function') return v051Api(action, payload || {}); return { ok: false, reason: 'api_not_ready' }; }
  function applyResult(result) { if (window.RinchanSync && typeof RinchanSync.applyApiResult === 'function') return RinchanSync.applyApiResult(result); return result; }
  function readIds() { return readJson('rinchanReadNewsIds', []); }
  function saveReadIds(ids) { return writeJson('rinchanReadNewsIds', Array.from(new Set((ids || []).filter(Boolean)))); }
  function dateKeyFromDate(date) { return date.getFullYear() + '-' + String(date.getMonth() + 1).padStart(2, '0') + '-' + String(date.getDate()).padStart(2, '0'); }
  function normalizeDateKey(value) { const raw = String(value || '').trim(); const iso = raw.match(/^(\d{4})[-/](\d{1,2})[-/](\d{1,2})/); if (iso) return iso[1] + '-' + String(iso[2]).padStart(2, '0') + '-' + String(iso[3]).padStart(2, '0'); const parsed = new Date(raw); if (!isNaN(parsed)) return dateKeyFromDate(parsed); return raw.slice(0, 10); }
  function activities() { const all = readJson('rinchanAllActivities', []); return Array.isArray(all) && all.length ? all : readJson('rinchanActivities', []); }
  function forestSummary() { return readJson('rinchanForestSummary', null); }
  function thanksTimeline() { return readJson('rinchanGoodTimeline', []); }
  function notices() { const custom = readJson('rinchanNotices', null); return Array.isArray(custom) ? custom : []; }
  function groupNews() { const custom = readJson('rinchanGroupNews', null); return Array.isArray(custom) && custom.length ? custom : [{ id: 'group-news-001', title: 'みんなで続ける健康習慣', body: '無理なく、できる範囲で歩数記録を続けましょう。', createdAt: new Date().toISOString(), icon: '🌳', tag: '健康' }]; }
  async function refreshPublicThanks() { const result = await api('thanksTimeline', {}); if (result && result.ok && Array.isArray(result.thanks)) { writeJson('rinchanGoodTimeline', result.thanks); renderAll(); return true; } return false; }
  function renderSummary() { const dateEl = document.getElementById('newsSummaryDate'); const statsEl = document.getElementById('forestSummaryStats'); if (dateEl) dateEl.textContent = formatMonthDay(new Date()); if (!statsEl) return; const server = forestSummary(); const today = dateKeyFromDate(new Date()); const acts = activities(); const todayRows = acts.filter(item => normalizeDateKey(item.date || item.createdAt || item.savedAt) === today); const todaySteps = server && Number(server.todaySteps || 0) > 0 ? Number(server.todaySteps || 0) : todayRows.reduce((sum, item) => sum + Number(item.steps || 0), 0); const todayCount = server && Number(server.todayActivities || 0) > 0 ? Number(server.todayActivities || 0) : todayRows.length; const totalSteps = server && Number(server.totalSteps || 0) > 0 ? Number(server.totalSteps || 0) : acts.reduce((sum, item) => sum + Number(item.steps || 0), 0); statsEl.innerHTML = [summaryStat('📝', todayCount.toLocaleString(), '今日の記録'), summaryStat('👟', todaySteps.toLocaleString(), '今日の歩数'), summaryStat('🌳', totalSteps.toLocaleString(), '累計歩数'), summaryStat('💌', thanksTimeline().length.toLocaleString(), 'ありがとう')].join(''); }
  function summaryStat(icon, value, label) { return '<div class="forest-summary-stat"><span class="forest-summary-stat-icon">' + icon + '</span><div><strong>' + value + '</strong><small>' + label + '</small></div></div>'; }
  function normalizeThanksItem(item, index) { const fromDept = item.fromDept || item.senderDept || item.fromDepartment || '杜の仲間'; const toDept = item.toDept || item.targetDept || item.receiverDept || item.toDepartment || '杜の仲間'; const reason = item.reason || item.message || 'ありがとう'; const createdAt = item.createdAt || item.savedAt || item.date || ''; return { id: item.thanksId || item.id || [fromDept, toDept, createdAt, reason, index].join('|'), from: fromDept, to: toDept, reason, createdAt, date: normalizeDateKey(createdAt), body: item.publicBody || item.body || '' }; }
  function thanksText(reason, count) { const base = reason && reason !== 'ありがとう' ? '「' + reason + '」のありがとう' : 'ありがとう'; return base + (count > 1 ? '　' + count + '件' : ''); }
  function thanksRows() { const groups = {}; thanksTimeline().filter(Boolean).map(normalizeThanksItem).forEach(item => { const key = [item.date, item.from, item.to, item.reason].join('|'); if (!groups[key]) groups[key] = Object.assign({}, item, { count: 0, latestAt: item.createdAt, ids: {} }); const g = groups[key]; const id = item.id || key + g.count; if (!g.ids[id]) { g.ids[id] = true; g.count += 1; } if (String(item.createdAt || '') > String(g.latestAt || '')) g.latestAt = item.createdAt; }); return Object.keys(groups).map(key => { const g = groups[key]; g.body = thanksText(g.reason, g.count); g.createdAt = g.latestAt || g.createdAt; return g; }).sort((a, b) => String(b.createdAt || '').localeCompare(String(a.createdAt || ''))); }
  function thanksCard(item) { return '<article class="thanks-card-item thanks-story-item compact-thanks-card"><div class="thanks-card-route"><span>💌</span><strong>' + escapeHtml(item.from) + ' → ' + escapeHtml(item.to) + '</strong><time>' + formatDate(item.createdAt) + '</time></div><p class="thanks-card-simple-text">' + escapeHtml(item.body) + '</p></article>'; }
  function renderThanksFlowSummary() { const box = document.getElementById('thanksFlowSummary'); const list = document.getElementById('thanksStoryList'); if (!box) return; const rows = thanksRows(); if (!rows.length) { box.innerHTML = '<div class="thanks-flow-empty"><span>💌</span><p>まだありがとうはありません。</p><small>杜ページから、仲間にありがとうを届けられます。</small></div>'; if (list) list.innerHTML = ''; return; } box.innerHTML = rows.slice(0, 1).map(thanksCard).join(''); if (list) list.innerHTML = rows.slice(1, 5).map(thanksCard).join(''); }
  function renderNotices() { const section = document.getElementById('noticeSection'); if (section) section.remove(); const box = document.getElementById('noticeList'); if (box) box.innerHTML = ''; }
  function renderGroupNews() { const box = document.getElementById('groupNewsList'); if (!box) return; const rows = groupNews().slice().sort((a, b) => String(b.createdAt || '').localeCompare(String(a.createdAt || ''))).slice(0, 3); if (!rows.length) { box.innerHTML = '<p class="empty-note news-empty">グループニュースはありません。</p>'; return; } box.innerHTML = rows.map(item => '<article class="group-news-item"><div class="group-news-icon">' + escapeHtml(item.icon || '📣') + '</div><div class="group-news-body"><div class="group-news-meta"><span class="group-news-tag">' + escapeHtml(item.tag || 'お知らせ') + '</span><time>' + formatDate(item.createdAt) + '</time></div><h3>' + escapeHtml(item.title || 'グループニュース') + '</h3><p>' + escapeHtml(item.body || '') + '</p></div></article>').join(''); }
  function updateBadges() { const count = notices().filter(item => !readIds().includes(item.id)).length; document.querySelectorAll('.notify-badge').forEach(badge => { badge.textContent = String(count); badge.classList.toggle('hidden', count <= 0); }); }
  async function markRead(newsId) { if (!newsId) return; const ids = readIds(); if (!ids.includes(newsId)) ids.push(newsId); saveReadIds(ids); renderNotices(); updateBadges(); const id = employeeId(); if (id) applyResult(await api('markNewsRead', { employeeId: id, newsId })); }
  function renderAll() { renderSummary(); renderThanksFlowSummary(); renderNotices(); renderGroupNews(); updateBadges(); }
  function formatMonthDay(value) { const d = value instanceof Date ? value : new Date(value || ''); if (isNaN(d)) return ''; const days = ['日','月','火','水','木','金','土']; return (d.getMonth()+1)+'/'+d.getDate()+' '+days[d.getDay()]; }
  function formatDate(value) { const d = new Date(value || ''); if (isNaN(d)) return ''; return (d.getMonth()+1)+'/'+d.getDate()+' '+String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0'); }
  function escapeHtml(value) { return String(value || '').replace(/[&<>'"]/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[c])); }
  function escapeAttr(value) { return escapeHtml(value).replace(/`/g, '&#96;'); }
  function install() { renderAll(); setTimeout(refreshPublicThanks, 200); window.v100RenderSummary = renderSummary; window.v100RenderThanksFlowSummary = renderThanksFlowSummary; window.v100RenderThanksStories = renderThanksFlowSummary; window.v100RenderNotices = renderNotices; window.v100RenderGroupNews = renderGroupNews; window.updateNewsBadgesV051 = updateBadges; window.updateNewsRowsV051 = renderNotices; window.openNews = markRead; window.markNoticeReadV113 = markRead; }
  document.addEventListener('DOMContentLoaded', install);
  return { VERSION, install, renderAll, renderSummary, renderThanksFlowSummary, refreshPublicThanks, renderNotices, renderGroupNews, updateBadges, markRead };
})();
window.RinchanNews = RinchanNews;
