const RinchanNews = (() => {
  const VERSION = 'v1.5.24';
  let serverPublicNotices = null;

  function readJson(key, fallback) { if (window.RinchanStorage && typeof RinchanStorage.readJson === 'function') return RinchanStorage.readJson(key, fallback); try { const raw = localStorage.getItem(key); return raw ? JSON.parse(raw) : fallback; } catch (e) { return fallback; } }
  function writeJson(key, value) { if (window.RinchanStorage && typeof RinchanStorage.writeJson === 'function') return RinchanStorage.writeJson(key, value); localStorage.setItem(key, JSON.stringify(value)); return value; }
  function participant() { if (window.RinchanStorage && typeof RinchanStorage.getParticipant === 'function') return RinchanStorage.getParticipant(); return readJson('rinchanParticipant', null); }
  function employeeId() { const user = participant(); return user && (user.employeeId || user.id || user.participantId) ? String(user.employeeId || user.id || user.participantId) : ''; }
  async function api(action, payload) { if (window.RinchanApi && typeof RinchanApi.request === 'function') return RinchanApi.request(action, payload || {}); if (typeof v051Api === 'function') return v051Api(action, payload || {}); return { ok: false, reason: 'api_not_ready' }; }
  function arrayUnique(list) { return Array.from(new Set((list || []).map(String).filter(Boolean))); }
  function userReads() { const r = readJson('rinchanUserReads', {}); return r && typeof r === 'object' ? r : {}; }
  function readIds() { const r = userReads(); return arrayUnique([].concat(readJson('rinchanReadNewsIds', []), r.readNewsIds || [])); }
  function saveReadIds(ids) { const next = arrayUnique(ids); writeJson('rinchanReadNewsIds', next); const r = userReads(); r.readNewsIds = next; r.updatedAt = new Date().toISOString(); writeJson('rinchanUserReads', r); return next; }
  function readFlowerIds() { const r = userReads(); return arrayUnique([].concat(readJson('rinchanReadThanksFlowerIds', []), r.readThanksFlowerIds || [])); }
  function saveFlowerIds(ids) { const next = arrayUnique(ids); writeJson('rinchanReadThanksFlowerIds', next); const r = userReads(); r.readThanksFlowerIds = next; r.updatedAt = new Date().toISOString(); writeJson('rinchanUserReads', r); return next; }
  function dateKeyFromDate(date) { return date.getFullYear() + '-' + String(date.getMonth() + 1).padStart(2, '0') + '-' + String(date.getDate()).padStart(2, '0'); }
  function normalizeDateKey(value) { const raw = String(value || '').trim(); const iso = raw.match(/^(\d{4})[-/](\d{1,2})[-/](\d{1,2})/); if (iso) return iso[1] + '-' + String(iso[2]).padStart(2, '0') + '-' + String(iso[3]).padStart(2, '0'); const parsed = new Date(raw); if (!isNaN(parsed)) return dateKeyFromDate(parsed); return raw.slice(0, 10); }
  function activities() { const all = readJson('rinchanAllActivities', []); return Array.isArray(all) && all.length ? all : readJson('rinchanActivities', []); }
  function forestSummary() { return readJson('rinchanForestSummary', null); }
  function thanksTimeline() { return readJson('rinchanGoodTimeline', []); }
  function senderLabel(type, fallback) { if (type === 'rinchan') return { icon: '🌱', name: 'りんちゃん' }; if (type === 'office') return { icon: '🏥', name: '事務局' }; if (type === 'group') return { icon: '🌳', name: '' }; return { icon: '🔔', name: fallback || 'お知らせ' }; }
  function normalizeNotice(item, fallbackType) { const type = item.type || item.senderType || fallbackType || 'office'; const sender = senderLabel(type, item.senderName); return Object.assign({}, item, { id: item.id || item.newsId || item.noticeId || ('notice-' + Date.now()), type, senderIcon: item.senderIcon || sender.icon, senderName: item.senderName || sender.name, icon: item.icon || sender.icon }); }

  function rinchanDailyNotice() { const now = new Date(); const key = dateKeyFromDate(now); const day = now.getDay(); let title = '今日のりんちゃん通信'; let body = '今日も無理せず、できる範囲で歩いてみましょう。小さな一歩でも、ちゃんと杜につながっています。'; if (day === 1) { title = '今週も小さな一歩から'; body = '月曜日です。今週も無理なく、まずは記録することから始めましょう。'; } else if (day === 5) { title = '今週の歩みをふりかえりましょう'; body = '金曜日です。たくさん歩けた人も、少しだけの人も、続けたことが大切です。'; } else if (day === 0 || day === 6) { title = '週末は体調優先で'; body = '週末は休むことも大切です。歩ける時に、できる範囲で大丈夫です。'; } const h = now.getHours(); if (h >= 18) body = '今日もおつかれさまでした。記録するだけでも、あなたの木は少しずつ育っています。'; return normalizeNotice({ id: 'rinchan-daily-' + key, title, body, createdAt: key + 'T08:00:00+09:00', type: 'rinchan', tag: '定期配信' }, 'rinchan'); }
  function defaultNotices() { return [rinchanDailyNotice(), normalizeNotice({ id: 'notice-welcome', title: 'りんちゃんの杜へようこそ', body: '歩数を記録して、みんなの杜を育てましょう。', createdAt: '2026-07-01T00:00:00+09:00', type: 'office', icon: '🏥' }), normalizeNotice({ id: 'notice-thanks', title: 'ありがとうを届けましょう', body: '杜ページから仲間にありがとうを送れます。', createdAt: '2026-07-01T00:00:00+09:00', type: 'office', icon: '🏥' })]; }
  function normalizeServerNotice(item) {
    const type = String(item && item.type || 'notice').trim().toLowerCase() === 'group' ? 'group' : 'notice';
    const id = String(item && (item.noticeId || item.id || item.newsId) || '').trim();
    const createdAt = String(item && (item.publishedAt || item.startAt || item.updatedAt || item.createdAt) || '').trim();
    const senderName = String(item && item.authorName || '').trim() || (type === 'group' ? 'グループ通信' : '事務局');
    const icon = type === 'group' ? '🌳' : '🏥';
    return normalizeNotice({
      id,
      type,
      title: String(item && item.title || ''),
      body: String(item && item.body || ''),
      createdAt,
      senderName,
      icon,
      tag: type === 'group' ? 'グループ' : 'お知らせ',
      targetType: String(item && item.targetType || 'all'),
      targetDept: String(item && item.targetDept || '')
    }, type);
  }
  function noticesFromServer() {
    const list = Array.isArray(serverPublicNotices) ? serverPublicNotices : [];
    return list
      .map(normalizeServerNotice)
      .filter(item => !!String(item.id || '').trim());
  }
  function localNotices() { const custom = readJson('rinchanNotices', null); const rows = Array.isArray(custom) && custom.length ? custom.map(item => normalizeNotice(item, item.type || 'office')) : defaultNotices(); const hasTodayRinchan = rows.some(item => String(item.id || '').indexOf('rinchan-daily-' + dateKeyFromDate(new Date())) === 0); const list = (hasTodayRinchan ? rows : [rinchanDailyNotice()].concat(rows)).map(item => normalizeNotice(item, item.type || 'office')); const map = {}; list.forEach(item => { map[String(item.id)] = item; }); return Object.values(map); }
  function notices() {
    const fromServer = noticesFromServer();
    if (fromServer.length) return fromServer;
    return localNotices();
  }
  function groupNewsAuto() { const server = forestSummary(); const acts = activities(); const today = dateKeyFromDate(new Date()); const todayRows = acts.filter(item => normalizeDateKey(item.date || item.createdAt || item.savedAt) === today); const todaySteps = server && Number(server.todaySteps || 0) > 0 ? Number(server.todaySteps || 0) : todayRows.reduce((sum, item) => sum + Number(item.steps || 0), 0); const todayCount = server && Number(server.todayActivities || 0) > 0 ? Number(server.todayActivities || 0) : todayRows.length; const thanksCount = thanksTimeline().length; let body = '今日もみんなの杜が少しずつ育っています。'; if (todaySteps > 0) body = '今日は全体で' + Number(todaySteps).toLocaleString() + '歩、' + Number(todayCount).toLocaleString() + '件の記録がありました。'; if (thanksCount > 0) body += ' ありがとうも' + Number(thanksCount).toLocaleString() + '件届いています。'; return { id: 'group-auto-' + today, title: '今日のグループニュース', body, createdAt: today + 'T12:00:00+09:00', icon: '🌳', tag: '自動集計', type: 'group' }; }
  function groupNews() { const custom = readJson('rinchanGroupNews', null); const base = Array.isArray(custom) && custom.length ? custom : [{ id: 'group-news-001', title: 'みんなで続ける健康習慣', body: '無理なく、できる範囲で歩数記録を続けましょう。', createdAt: '2026-07-01T00:00:00+09:00', icon: '🌳', tag: '健康', type: 'group' }]; const rows = [groupNewsAuto()].concat(base); const seen = {}; return rows.filter(item => { const id = String(item.id || ''); if (seen[id]) return false; seen[id] = true; return true; }); }
  async function refreshPublicThanks() { const result = await api('thanksTimeline', {}); if (result && result.ok && Array.isArray(result.thanks)) { writeJson('rinchanGoodTimeline', result.thanks); renderAll(); return true; } return false; }
  async function refreshPublicNotices() {
    const result = await api('publicNewsList', { employeeId: employeeId() });
    if (result && result.ok && Array.isArray(result.notices)) {
      serverPublicNotices = result.notices;
      renderNotices();
      updateBadges();
      return true;
    }
    return false;
  }
  function renderSummary() { const dateEl = document.getElementById('newsSummaryDate'); const statsEl = document.getElementById('forestSummaryStats'); if (dateEl) dateEl.textContent = formatMonthDay(new Date()); if (!statsEl) return; const server = forestSummary(); const today = dateKeyFromDate(new Date()); const acts = activities(); const todayRows = acts.filter(item => normalizeDateKey(item.date || item.createdAt || item.savedAt) === today); const todaySteps = server && Number(server.todaySteps || 0) > 0 ? Number(server.todaySteps || 0) : todayRows.reduce((sum, item) => sum + Number(item.steps || 0), 0); const todayCount = server && Number(server.todayActivities || 0) > 0 ? Number(server.todayActivities || 0) : todayRows.length; const totalSteps = server && Number(server.totalSteps || 0) > 0 ? Number(server.totalSteps || 0) : acts.reduce((sum, item) => sum + Number(item.steps || 0), 0); statsEl.innerHTML = [summaryStat('📝', todayCount.toLocaleString(), '今日の記録'), summaryStat('👟', todaySteps.toLocaleString(), '今日の歩数'), summaryStat('🌳', totalSteps.toLocaleString(), '累計歩数'), summaryStat('🌸', thanksTimeline().length.toLocaleString(), 'ありがとうの花')].join(''); }
  function summaryStat(icon, value, label) { return '<div class="forest-summary-stat"><span class="forest-summary-stat-icon">' + icon + '</span><div><strong>' + value + '</strong><small>' + label + '</small></div></div>'; }
  function normalizeThanksItem(item, index) { const fromDept = item.fromDept || item.senderDept || item.fromDepartment || '杜の仲間'; const toDept = item.toDept || item.targetDept || item.receiverDept || item.toDepartment || '杜の仲間'; const reason = item.reason || item.message || 'ありがとう'; const createdAt = item.createdAt || item.savedAt || item.date || ''; return { id: item.thanksId || item.id || [fromDept, toDept, createdAt, reason, index].join('|'), from: fromDept, to: toDept, reason, createdAt, date: normalizeDateKey(createdAt), body: item.publicBody || item.body || '' }; }
  function thanksText(reason, count) { const base = reason && reason !== 'ありがとう' ? '「' + reason + '」のありがとう' : 'ありがとう'; return base + (count > 1 ? '　' + count + '件' : ''); }
  function thanksRows() { const groups = {}; thanksTimeline().filter(Boolean).map(normalizeThanksItem).forEach(item => { const key = [item.date, item.from, item.to, item.reason].join('|'); if (!groups[key]) groups[key] = Object.assign({}, item, { count: 0, latestAt: item.createdAt, ids: {} }); const g = groups[key]; const id = item.id || key + g.count; if (!g.ids[id]) { g.ids[id] = true; g.count += 1; } if (String(item.createdAt || '') > String(g.latestAt || '')) g.latestAt = item.createdAt; }); return Object.keys(groups).map(key => { const g = groups[key]; g.body = thanksText(g.reason, g.count); g.createdAt = g.latestAt || g.createdAt; return g; }).sort((a, b) => String(b.createdAt || '').localeCompare(String(a.createdAt || ''))); }
  function sourceName(name) { return '<span class="news-source-name"><span class="news-source-text">' + escapeHtml(name || '') + '</span></span>'; }
  function thanksCard(item) { return '<article class="thanks-card-item thanks-story-item compact-thanks-card"><div class="thanks-card-route"><span>🌸</span><strong>' + escapeHtml(item.from) + ' → ' + escapeHtml(item.to) + '</strong><time>' + formatDate(item.createdAt) + '</time></div><p class="thanks-card-simple-text">' + escapeHtml(item.body) + '</p></article>'; }
  function renderThanksFlowSummary() { const box = document.getElementById('thanksFlowSummary'); const list = document.getElementById('thanksStoryList'); if (!box) return; const rows = thanksRows(); if (!rows.length) { box.innerHTML = '<div class="thanks-flow-empty"><span>🌸</span><p>まだありがとうはありません。</p><small>杜ページから、仲間にありがとうを届けられます。</small></div>'; if (list) list.innerHTML = ''; return; } box.innerHTML = rows.slice(0, 1).map(thanksCard).join(''); if (list) list.innerHTML = rows.slice(1, 5).map(thanksCard).join(''); }

  function itemToId(item) { return String(item.toParticipantId || item.toEmployeeId || item.receiverId || item.receiverEmployeeId || item.toId || item.targetId || item.targetEmployeeId || item.to || '').trim(); }
  function allReceivedThanks() { const me = employeeId(); if (!me) return []; const sources = [readJson('rinchanReceivedThanks', []), readJson('rinchanThanks', [])]; const map = {}; sources.forEach(list => { if (!Array.isArray(list)) return; list.forEach(item => { const toId = itemToId(item || {}); if (toId && toId !== me) return; if (!toId && item.fromParticipantId && String(item.fromParticipantId) === me) return; const id = String(item.thanksId || item.id || item.createdAt || item.savedAt || JSON.stringify(item)); if (!id) return; map[id] = normalizeReceivedThanks(item, id); }); }); return Object.values(map).sort((a, b) => String(b.createdAt || '').localeCompare(String(a.createdAt || ''))); }
  function normalizeReceivedThanks(item, id) { return { id, fromName: item.fromName || item.senderName || item.fromEmployeeName || item.sender || item.from || '', fromDept: item.fromDept || item.senderDept || item.fromDepartment || '', toName: item.toName || '', reason: item.reason || 'ありがとう', comment: item.comment || item.message || item.publicBody || item.body || '', createdAt: item.createdAt || item.savedAt || item.date || '', raw: item }; }
  function flowerMainText(item) { const reason = String(item.reason || '').trim(); if (reason && reason !== 'ありがとう') return '「' + reason + '」'; const comment = String(item.comment || '').trim(); const quoted = comment.match(/「([^」]+)」/); if (quoted && quoted[1]) return '「' + quoted[1] + '」'; return 'ありがとう'; }
  function flowerFromText(item) { const dept = String(item.fromDept || '').trim(); const name = String(item.fromName || '').trim(); if (dept && name) return dept + '　' + name + 'さんより'; if (name && name !== '杜の仲間') return name + 'さんより'; if (dept) return dept + 'より'; return '杜の仲間より'; }
  function receivedThanksCard(item) { const read = readFlowerIds().includes(item.id); const main = flowerMainText(item); const from = flowerFromText(item); const action = read ? '<span class="received-thanks-done">🌸 受け取り済み</span>' : '<button type="button" class="received-thanks-receive" onclick="event.stopPropagation();RinchanNews.receiveFlower(\'' + escapeAttr(item.id) + '\')">花を受け取る</button>'; return '<article class="received-thanks-item ' + (read ? 'is-read' : 'is-unread') + '"' + (read ? '' : ' onclick="RinchanNews.receiveFlower(\'' + escapeAttr(item.id) + '\')"') + '><span class="received-thanks-flower">' + (read ? '🌸' : '🌷') + '</span><span class="received-thanks-main"><strong>' + escapeHtml(main) + '</strong><span class="received-thanks-from">' + escapeHtml(from) + '</span><time>' + formatDate(item.createdAt) + '</time><span class="received-thanks-actions">' + action + '</span></span></article>'; }
  function renderReceivedThanks() { const box = document.getElementById('receivedThanksList'); if (!box) return; const rows = allReceivedThanks().slice(0, 20); if (!rows.length) { box.innerHTML = '<p class="received-thanks-empty">まだ届いた花はありません。<br>ありがとうが届くと、ここに花が咲きます🌸</p>'; return; } box.innerHTML = rows.map(receivedThanksCard).join(''); }
  function receiveFlower(id) { const item = allReceivedThanks().find(row => String(row.id) === String(id)); if (!item) return; const ids = readFlowerIds(); const wasUnread = !ids.includes(item.id); if (wasUnread) ids.push(item.id); saveFlowerIds(ids); renderReceivedThanks(); updateBadges(); if (window.RinchanThanksHomeNotice && typeof RinchanThanksHomeNotice.render === 'function') RinchanThanksHomeNotice.render(); if (wasUnread) { api('markThanksRead', { employeeId: employeeId(), thanksId: item.id, readThanksFlowerIds: readFlowerIds() }).catch(() => {}); if (window.RinchanModal && typeof RinchanModal.show === 'function') RinchanModal.show({ speech: 'ありがとうの花を\n受け取ったよ🌸', note: flowerFromText(item) + '\n' + flowerMainText(item), primaryText: 'ありがとう♪', hideClose: true }); } }
  function openReceivedThanks(id) { receiveFlower(id); }
  function scrollToFlowers() { const el = document.getElementById('receivedThanksList') || document.querySelector('.received-thanks-card'); if (!el) return; setTimeout(() => { (document.querySelector('.received-thanks-card') || el).scrollIntoView({ behavior: 'smooth', block: 'start' }); }, 250); }

  function renderNotices() { const box = document.getElementById('noticeList'); if (!box) return; const read = readIds(); const rows = notices().slice().sort((a, b) => String(b.createdAt || '').localeCompare(String(a.createdAt || ''))).slice(0, 5); if (!rows.length) { box.innerHTML = '<p class="empty-note news-empty">お知らせはありません。</p>'; return; } box.innerHTML = rows.map(item => { const isRead = read.includes(String(item.id)); const action = isRead ? '' : '<button type="button" class="notice-confirm" onclick="RinchanNews.markRead(\'' + escapeAttr(item.id) + '\')">確認</button>'; return '<article class="notice-item-v1040 ' + (isRead ? 'is-read' : 'unread') + ' notice-' + escapeAttr(item.type || 'office') + '"><span class="notice-avatar-v1040">' + escapeHtml(item.icon || item.senderIcon || '🔔') + '</span><div class="notice-content-v1040"><div class="notice-top-v1040"><div class="notice-source-wrap-v1040">' + sourceName(item.senderName) + '</div><time>' + formatDate(item.createdAt) + '</time></div><div class="notice-actions-v1040"><span class="notice-state">' + (isRead ? '既読' : '未読') + '</span>' + action + '</div><strong>' + escapeHtml(item.title || 'お知らせ') + '</strong><p>' + escapeHtml(item.body || '') + '</p></div></article>'; }).join(''); }
  function renderGroupNews() { const box = document.getElementById('groupNewsList'); if (!box) return; const rows = groupNews().slice().sort((a, b) => String(b.createdAt || '').localeCompare(String(a.createdAt || ''))).slice(0, 4); if (!rows.length) { box.innerHTML = '<p class="empty-note news-empty">グループニュースはありません。</p>'; return; } box.innerHTML = rows.map(item => '<article class="group-news-item-v1040"><div class="group-news-avatar-v1040">' + escapeHtml(item.icon || '🌳') + '</div><div class="group-news-content-v1040"><div class="group-news-top-v1040"><div class="group-news-source-v1040"></div><div class="group-news-side-v1040"><span class="group-news-tag">' + escapeHtml(item.tag || 'お知らせ') + '</span><time>' + formatDate(item.createdAt) + '</time></div></div><h3>' + escapeHtml(item.title || 'グループニュース') + '</h3><p>' + escapeHtml(item.body || '') + '</p></div></article>').join(''); }
  function updateBadges() { const read = readIds(); const unreadNotices = notices().filter(item => !read.includes(String(item.id))).length; const me = employeeId(); const unreadFlowers = me ? allReceivedThanks().filter(item => !readFlowerIds().includes(String(item.id))).length : 0; const count = unreadNotices + unreadFlowers; document.querySelectorAll('.notify-badge').forEach(badge => { badge.textContent = String(count); badge.classList.toggle('hidden', count <= 0); }); }
  async function markRead(newsId) { if (!newsId) return; const ids = readIds(); if (!ids.includes(String(newsId))) ids.push(String(newsId)); saveReadIds(ids); renderNotices(); updateBadges(); try { await api('markNewsRead', { employeeId: employeeId(), newsId: String(newsId), readNewsIds: readIds() }); } catch (e) { if (window.RinchanOfflineQueue && typeof RinchanOfflineQueue.enqueue === 'function') RinchanOfflineQueue.enqueue('markNewsRead', { employeeId: employeeId(), newsId: String(newsId), readNewsIds: readIds() }, e.message || 'send_failed'); } }
  function renderAll() { renderSummary(); renderReceivedThanks(); renderThanksFlowSummary(); renderNotices(); renderGroupNews(); updateBadges(); if (location.hash === '#flowers') scrollToFlowers(); }
  function formatMonthDay(value) { const d = value instanceof Date ? value : new Date(value || ''); if (isNaN(d)) return ''; const days = ['日','月','火','水','木','金','土']; return (d.getMonth()+1)+'/'+d.getDate()+' '+days[d.getDay()]; }
  function formatDate(value) { const d = new Date(value || ''); if (isNaN(d)) return ''; return (d.getMonth()+1)+'/'+d.getDate()+' '+String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0'); }
  function escapeHtml(value) { return String(value || '').replace(/[&<>'"]/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[c])); }
  function escapeAttr(value) { return escapeHtml(value).replace(/`/g, '&#96;'); }
  function install() { renderAll(); setTimeout(refreshPublicThanks, 200); setTimeout(refreshPublicNotices, 250); if (location.hash === '#flowers') setTimeout(scrollToFlowers, 700); window.v100RenderSummary = renderSummary; window.v100RenderThanksFlowSummary = renderThanksFlowSummary; window.v100RenderThanksStories = renderThanksFlowSummary; window.v100RenderNotices = renderNotices; window.v100RenderGroupNews = renderGroupNews; window.updateNewsBadgesV051 = updateBadges; window.updateNewsRowsV051 = renderNotices; window.openNews = markRead; window.markNoticeReadV113 = markRead; }
  document.addEventListener('DOMContentLoaded', install);
  return { VERSION, install, renderAll, renderSummary, renderReceivedThanks, renderThanksFlowSummary, refreshPublicThanks, refreshPublicNotices, renderNotices, renderGroupNews, updateBadges, markRead, openReceivedThanks, receiveFlower, scrollToFlowers, rinchanDailyNotice, groupNewsAuto, allReceivedThanks };
})();
window.RinchanNews = RinchanNews;