const RinchanThanks = (() => {
  const VERSION = 'v1.1.30';

  function readJson(key, fallback) { if (window.RinchanStorage) return RinchanStorage.readJson(key, fallback); try { const raw = localStorage.getItem(key); return raw ? JSON.parse(raw) : fallback; } catch (e) { return fallback; } }
  function writeJson(key, value) { if (window.RinchanStorage) return RinchanStorage.writeJson(key, value); localStorage.setItem(key, JSON.stringify(value)); return value; }
  function participant() { if (window.RinchanStorage) return RinchanStorage.getParticipant(); return readJson('rinchanParticipant', null); }
  function employeeId() { const user = participant(); return user && (user.employeeId || user.id || user.participantId) ? String(user.employeeId || user.id || user.participantId) : ''; }
  function deviceId() { if (window.RinchanStorage) return RinchanStorage.deviceId(); let id = localStorage.getItem('rinchanDeviceId'); if (!id) { id = 'D' + Date.now().toString(36) + Math.random().toString(36).slice(2, 8); localStorage.setItem('rinchanDeviceId', id); } return id; }
  async function api(action, payload) { if (window.RinchanApi) return RinchanApi.request(action, payload || {}); if (typeof v051Api === 'function') return v051Api(action, payload || {}); if (typeof rinchanApi === 'function') return rinchanApi(action, payload || {}); return { ok: false, reason: 'api_not_ready' }; }
  function applyResult(result) { if (window.RinchanSync && typeof RinchanSync.applyApiResult === 'function') return RinchanSync.applyApiResult(result); if (typeof v135ApplyApiResult === 'function') return v135ApplyApiResult(result); return result; }
  function enqueueOffline(action, payload, reason) { if (window.RinchanOfflineQueue && typeof RinchanOfflineQueue.enqueue === 'function') { RinchanOfflineQueue.enqueue(action, payload || {}, reason || 'send_failed'); return; } const list = readJson('rinchanPendingQueue', []); const key = action + ':' + String((payload && (payload.thanksId || payload.id)) || Date.now()); if (!list.some(item => item.key === key)) { list.push({ id: 'Q' + Date.now().toString(36), key, action, payload: payload || {}, reason: reason || 'send_failed', retryCount: 0, createdAt: new Date().toISOString(), lastTriedAt: '' }); writeJson('rinchanPendingQueue', list.slice(-50)); } if (window.RinchanSync && typeof RinchanSync.setStatus === 'function') RinchanSync.setStatus('error', '通信できないため未送信として保存しました。'); }
  function normalizeThanks(item) { return Object.assign({}, item || {}, { thanksId: String((item && (item.thanksId || item.id)) || 'K' + Date.now().toString(36) + Math.random().toString(36).slice(2, 6)), fromParticipantId: String((item && item.fromParticipantId) || ''), fromName: String((item && item.fromName) || ''), fromDept: String((item && (item.fromDept || item.senderDept || item.fromDepartment)) || ''), toParticipantId: String((item && (item.toParticipantId || item.toEmployeeId || item.receiverId || item.receiverEmployeeId || item.toId || item.targetId || item.targetEmployeeId || item.to)) || ''), toName: String((item && item.toName) || ''), toDept: String((item && item.toDept) || ''), reason: String((item && item.reason) || 'ありがとう'), comment: String((item && (item.comment || item.message || item.publicBody || item.body)) || ''), createdAt: String((item && (item.createdAt || item.savedAt || item.date)) || new Date().toISOString()), version: String((item && item.version) || VERSION) }); }
  function receivedThanks() { const me = employeeId(); const sources = [readJson('rinchanReceivedThanks', []), readJson('rinchanThanks', []), readJson('rinchanGoodTimeline', [])]; const map = {}; sources.forEach(list => { if (!Array.isArray(list)) return; list.forEach(raw => { const item = normalizeThanks(raw); if (me && item.toParticipantId && item.toParticipantId !== me) return; const id = String(item.thanksId || item.id || item.createdAt || JSON.stringify(item)); if (!id) return; map[id] = Object.assign({}, item, { thanksId: id }); }); }); return Object.values(map).sort((a, b) => String(b.createdAt || '').localeCompare(String(a.createdAt || ''))); }
  function sentThanks() { return readJson('rinchanSentThanks', []); }
  function timeline() { return readJson('rinchanGoodTimeline', []); }
  function readFlowerIds() { const ids = readJson('rinchanReadThanksFlowerIds', []); return Array.isArray(ids) ? ids.map(String) : []; }
  function saveFlowerIds(ids) { return writeJson('rinchanReadThanksFlowerIds', Array.from(new Set((ids || []).map(String).filter(Boolean)))); }
  function stats() { const s = readJson('rinchanThanksStats', null); if (s) return s; return { sentCount: sentThanks().length, receivedCount: receivedThanks().length, totalCount: sentThanks().length + receivedThanks().length }; }
  function addLocalSent(item) { const list = sentThanks(); const next = normalizeThanks(item); const index = list.findIndex(row => String(row.thanksId || '') === next.thanksId); if (index >= 0) list[index] = Object.assign({}, list[index], next); else list.unshift(next); writeJson('rinchanSentThanks', list.slice(0, 50)); writeJson('rinchanThanksStats', { sentCount: list.length, receivedCount: receivedThanks().length, totalCount: list.length + receivedThanks().length }); renderStats(); return next; }
  function buildPayload(toUser, reason) { const from = participant(); if (!from || !(from.employeeId || from.id)) return null; const to = toUser || {}; return normalizeThanks({ thanksId: 'K' + Date.now().toString(36) + Math.random().toString(36).slice(2, 6), fromParticipantId: from.employeeId || from.id, fromName: from.nick || from.name || '杜の仲間', fromDept: from.dept || '', toParticipantId: to.employeeId || to.id || to.participantId || '', toName: to.nick || to.name || '杜の仲間', toDept: to.dept || to.toDept || '', reason: reason || to.reason || 'ありがとう', createdAt: new Date().toISOString(), deviceId: deviceId(), version: VERSION }); }
  function refreshLocalViews() { try { renderAll(); } catch (e) {} try { if (window.renderV070Mypage) window.renderV070Mypage(); } catch (e) {} try { if (window.v100RenderThanksFlowSummary) window.v100RenderThanksFlowSummary(); } catch (e) {} try { if (window.RinchanThanksHomeNotice && RinchanThanksHomeNotice.render) RinchanThanksHomeNotice.render(); } catch (e) {} try { if (window.RinchanOfflineQueue && RinchanOfflineQueue.renderStatus) RinchanOfflineQueue.renderStatus(); } catch (e) {} }
  async function syncThanksInBackground(payload) { try { if (window.RinchanSync && RinchanSync.setStatus) RinchanSync.setStatus('syncing', 'ありがとうを同期中です。'); const result = await api('saveThanks', payload); if (result && result.ok) { applyResult(result); if (window.RinchanSync && RinchanSync.setStatus) RinchanSync.setStatus('synced', ''); refreshLocalViews(); return true; } enqueueOffline('saveThanks', payload, (result && (result.reason || result.error)) || 'send_failed'); return false; } catch (e) { enqueueOffline('saveThanks', payload, e.message || 'send_failed'); return false; } }
  async function sendThanks(toUser, reason) { const payload = buildPayload(toUser, reason); if (!payload || !payload.toParticipantId) { alert('ありがとうを送る相手を選んでください。'); return null; } const saved = addLocalSent(payload); refreshLocalViews(); setTimeout(() => syncThanksInBackground(saved || payload), 20); return { ok: true, local: true, queued: true, thanks: saved || payload }; }
  function sendThanksFromDataset(button) { const el = button || (event && event.currentTarget) || null; if (!el) return; const data = el.dataset || {}; const toUser = { id: data.id || data.participantId || data.toParticipantId || '', employeeId: data.employeeId || data.id || data.participantId || data.toParticipantId || '', name: data.name || data.toName || '', nick: data.nick || '', dept: data.dept || data.toDept || '' }; const reason = data.reason || 'ありがとう'; return sendThanks(toUser, reason); }
  function renderStats() { const s = stats(); const sent = document.getElementById('v139SentThanksCount'); const received = document.getElementById('v139ReceivedThanksCount'); const total = document.getElementById('v139TotalThanksCount'); if (sent) sent.textContent = Number(s.sentCount || 0).toLocaleString() + '件'; if (received) received.textContent = Number(s.receivedCount || receivedThanks().length || 0).toLocaleString() + '件'; if (total) total.textContent = Number(s.totalCount || (sentThanks().length + receivedThanks().length) || 0).toLocaleString() + '件'; }
  function flowerMainText(item) { const reason = String(item.reason || '').trim(); if (reason && reason !== 'ありがとう') return '「' + reason + '」'; const comment = String(item.comment || '').trim(); const quoted = comment.match(/「([^」]+)」/); if (quoted && quoted[1]) return '「' + quoted[1] + '」'; return 'ありがとう'; }
  function flowerFromText(item) { const dept = String(item.fromDept || '').trim(); const name = String(item.fromName || '').trim(); if (dept && name) return dept + '　' + name + 'さんより'; if (name && name !== '杜の仲間') return name + 'さんより'; if (dept) return dept + 'より'; return '杜の仲間より'; }
  function flowerCard(item, mode) { const id = String(item.thanksId || item.id || ''); const isInbox = mode === 'inbox'; const action = isInbox ? '<button type="button" class="received-thanks-receive" onclick="RinchanThanks.receiveFlower(\'' + escapeAttr(id) + '\')">花を受け取る</button>' : '<span class="received-thanks-done">🌸 受け取り済み</span>'; return '<article class="received-thanks-item ' + (isInbox ? 'is-unread' : 'is-read') + '"><span class="received-thanks-flower">' + (isInbox ? '🌷' : '🌸') + '</span><span class="received-thanks-main"><strong>' + escapeHtml(flowerMainText(item)) + '</strong><span class="received-thanks-from">' + escapeHtml(flowerFromText(item)) + '</span><time>' + formatDate(item.createdAt) + '</time><span class="received-thanks-actions">' + action + '</span></span></article>'; }
  function renderReceivedList() { const inboxSection = document.getElementById('thanksInboxSection'); const inbox = document.getElementById('thanksInboxList'); const history = document.getElementById('receivedThanksList'); const rows = receivedThanks(); const opened = readFlowerIds(); const unread = rows.filter(item => !opened.includes(String(item.thanksId || item.id || ''))); const read = rows.filter(item => opened.includes(String(item.thanksId || item.id || ''))); if (inboxSection) inboxSection.classList.toggle('hidden', unread.length <= 0); if (inbox) inbox.innerHTML = unread.map(item => flowerCard(item, 'inbox')).join(''); if (history) { const historyRows = (read.length ? read : rows).slice(0, 20); if (!historyRows.length) history.innerHTML = '<p class="received-thanks-empty">まだありがとう履歴はありません。</p>'; else history.innerHTML = historyRows.map(item => flowerCard(item, 'history')).join(''); } }
  function receiveFlower(id) { const rows = receivedThanks(); const item = rows.find(row => String(row.thanksId || row.id || '') === String(id)); if (!item) return; const ids = readFlowerIds(); if (!ids.includes(String(id))) ids.push(String(id)); saveFlowerIds(ids); renderAll(); try { if (window.RinchanThanksHomeNotice && RinchanThanksHomeNotice.render) RinchanThanksHomeNotice.render(); } catch (e) {} if (window.RinchanModal && typeof RinchanModal.show === 'function') RinchanModal.show({ speech: 'ありがとうの花を\n受け取ったよ🌸', note: flowerFromText(item) + '\n' + flowerMainText(item), primaryText: 'ありがとう♪', hideClose: true }); }
  function renderTimelineSummary() { const box = document.getElementById('thanksFlowSummary'); if (!box) return; const rows = timeline().slice().sort((a, b) => String(b.createdAt || '').localeCompare(String(a.createdAt || ''))); if (!rows.length) { box.innerHTML = '<p class="empty-note news-empty">まだありがとうは届いていません。</p>'; return; } const item = rows[0]; box.innerHTML = '<div class="thanks-flow-main"><strong>' + escapeHtml(item.title || 'ありがとうが届けられました') + '</strong><p>' + escapeHtml(item.publicBody || item.body || '') + '</p><small>' + formatDate(item.createdAt) + '</small></div>'; }
  function renderTimelineList() { const box = document.getElementById('thanksStoryList'); if (!box) return; const rows = timeline().slice().sort((a, b) => String(b.createdAt || '').localeCompare(String(a.createdAt || ''))).slice(0, 10); if (!rows.length) { box.innerHTML = ''; return; } box.innerHTML = rows.map(item => { const reason = item.reason ? '<span class="thanks-reason-pill">' + escapeHtml(item.reason) + '</span>' : ''; return '<div class="thanks-story-row"><div><strong>' + escapeHtml(item.fromDept || '杜の仲間') + ' → ' + escapeHtml(item.toDept || item.targetDept || '杜の仲間') + '</strong><p>' + escapeHtml(item.publicBody || item.body || '') + '</p></div>' + reason + '</div>'; }).join(''); }
  function renderAll() { renderStats(); renderReceivedList(); renderTimelineSummary(); renderTimelineList(); }
  function formatDate(value) { const d = new Date(value || ''); if (isNaN(d)) return ''; return (d.getMonth() + 1) + '/' + d.getDate() + ' ' + String(d.getHours()).padStart(2, '0') + ':' + String(d.getMinutes()).padStart(2, '0'); }
  function escapeHtml(value) { return String(value || '').replace(/[&<>'"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c])); }
  function escapeAttr(value) { return escapeHtml(value).replace(/`/g, '&#96;'); }
  function install() { renderAll(); window.v113LoadReceivedThanks = renderReceivedList; window.v100RenderThanksFlowSummary = renderTimelineSummary; window.v100RenderThanksStories = renderTimelineList; }
  document.addEventListener('DOMContentLoaded', install);
  return { VERSION, install, sendThanks, sendThanksFromDataset, receiveFlower, renderAll, renderStats, renderReceivedList, renderTimelineSummary, renderTimelineList, addLocalSent };
})();
window.RinchanThanks = RinchanThanks;
