const SHEET_USERS='users';
const SHEET_ACTIVITIES='activities';
const SHEET_THANKS='thanks';
const SHEET_LOGS='logs';
const VERSION='v0.9.20';

function doGet(e){const action=e&&e.parameter?String(e.parameter.action||''):'';const ss=SpreadsheetApp.getActiveSpreadsheet();const setup=setupProject(ss);if(action==='setup')return jsonOutput({ok:true,action,setup,version:VERSION});if(action==='dashboard')return jsonOutput({ok:true,action,data:getDashboard(ss),version:VERSION});if(action==='adminStats')return jsonOutput({ok:true,action,data:getAdminStats(ss),version:VERSION});return jsonOutput({ok:true,app:'RinchanMori',version:VERSION,setup,message:'Apps Script is running.'});}
function doPost(e){try{const data=parseRequest(e);const action=String(data.action||'').trim();const ss=SpreadsheetApp.getActiveSpreadsheet();setupProject(ss);if(action==='setup')return jsonOutput({ok:true,action,setup:setupProject(ss),version:VERSION});if(action==='dashboard')return jsonOutput({ok:true,action,data:getDashboard(ss),version:VERSION});if(action==='adminStats')return jsonOutput({ok:true,action,data:getAdminStats(ss),version:VERSION});if(action==='saveUser'){const saved=saveUser(ss,data);writeLog(ss,action,data.deviceId,saved.user.id,'ok','');return jsonOutput({ok:true,action,saved,user:saved.user,version:VERSION});}if(action==='loginUser'){const user=loginUser(ss,data);writeLog(ss,action,data.deviceId,user?user.id:'',user?'ok':'ng',user?'':'login_failed');if(!user)return jsonOutput({ok:false,error:'login_failed',version:VERSION});return jsonOutput({ok:true,action,user,version:VERSION});}if(action==='saveActivity'){const saved=saveActivity(ss,data);writeLog(ss,action,data.deviceId,data.participantId||data.id,'ok','');return jsonOutput({ok:true,action,saved,version:VERSION});}if(action==='deleteActivity'){const deleted=deleteActivity(ss,data);writeLog(ss,action,data.deviceId,data.participantId||data.id,deleted.deleted?'ok':'ng',deleted.deleted?'':'not_found');return jsonOutput({ok:true,action,deleted,version:VERSION});}if(action==='saveThanks'){const saved=saveThanks(ss,data);writeLog(ss,action,data.fromParticipantId||data.deviceId,data.toParticipantId,'ok','');return jsonOutput({ok:true,action,saved,version:VERSION});}if(action==='myThanks'){const thanks=getMyThanks(ss,data);writeLog(ss,action,data.deviceId,data.employeeId||data.id||data.toParticipantId,'ok','');return jsonOutput({ok:true,action,thanks,version:VERSION});}writeLog(ss,action||'unknown',data.deviceId,data.participantId||data.id,'ng','unknown_action');return jsonOutput({ok:false,error:'unknown_action',version:VERSION});}catch(err){try{const ss=SpreadsheetApp.getActiveSpreadsheet();setupProject(ss);writeLog(ss,'error','','','ng',err.message);}catch(ignore){}return jsonOutput({ok:false,error:err.message,version:VERSION});}}
function setupProjectManual(){return setupProject(SpreadsheetApp.getActiveSpreadsheet());}
function parseRequest(e){if(!e||!e.postData||!e.postData.contents)return{};return JSON.parse(e.postData.contents);}
function jsonOutput(obj){return ContentService.createTextOutput(JSON.stringify(obj)).setMimeType(ContentService.MimeType.JSON);}
function setupProject(ss){const usersSheet=ensureSheet(ss,SHEET_USERS,['id','deviceId','name','dept','nick','declaration','weeklyGoal','createdAt','updatedAt','version','lastSavedAt','email','pin4','employeeId']);usersSheet.getRange(1,13,Math.max(usersSheet.getMaxRows(),1),1).setNumberFormat('@');normalizeExistingPin4(usersSheet);ensureSheet(ss,SHEET_ACTIVITIES,['activityId','participantId','deviceId','date','steps','challenge','comment','createdAt','version','savedAt']);ensureSheet(ss,SHEET_THANKS,['thanksId','fromParticipantId','fromName','toParticipantId','toName','toDept','reason','createdAt','version','savedAt']);ensureSheet(ss,SHEET_LOGS,['loggedAt','action','deviceId','participantId','status','message']);return{spreadsheetId:ss.getId(),sheets:ss.getSheets().map(s=>s.getName())};}
function ensureSheet(ss,name,headers){let sheet=ss.getSheetByName(name);if(!sheet)sheet=ss.insertSheet(name);if(sheet.getMaxColumns()<headers.length)sheet.insertColumnsAfter(sheet.getMaxColumns(),headers.length-sheet.getMaxColumns());const current=sheet.getRange(1,1,1,headers.length).getValues()[0];headers.forEach((h,i)=>{if(current[i]!==h)sheet.getRange(1,i+1).setValue(h);});if(sheet.getFrozenRows()!==1)sheet.setFrozenRows(1);sheet.autoResizeColumns(1,headers.length);return sheet;}
function normalizeExistingPin4(sheet){const lastRow=sheet.getLastRow();if(lastRow<2)return;const range=sheet.getRange(2,13,lastRow-1,1);const values=range.getValues();let changed=false;const fixed=values.map(row=>{const pin=normalizePin(row[0]);if(pin&&String(row[0])!==pin)changed=true;return[pin||''];});if(changed)range.setValues(fixed);}
function saveUser(ss,data){const sheet=ss.getSheetByName(SHEET_USERS);const employeeId=normalizeEmployeeId(data.employeeId||data.id||data.participantId||'');if(!employeeId)throw new Error('employee_id_required');const row=findRowByValue(sheet,1,employeeId);const old=row>0?rowToObject(sheet,row):{};const now=new Date().toISOString();const user={id:employeeId,employeeId,deviceId:data.deviceId||old.deviceId||'',name:data.name||old.name||'',dept:data.dept||old.dept||'',nick:data.nick||old.nick||'',declaration:data.declaration!==undefined?data.declaration:(old.declaration||''),weeklyGoal:data.weeklyGoal||old.weeklyGoal||'まずは無理なく続ける',createdAt:data.createdAt||old.createdAt||now,updatedAt:data.updatedAt||now,version:data.version||data.appVersion||VERSION,lastSavedAt:now,email:normalizeEmail(data.email||'')||old.email||'',pin4:normalizePin(data.pin4||'')||normalizePin(old.pin4||'')||''};const values=[user.id,user.deviceId,user.name,user.dept,user.nick,user.declaration,user.weeklyGoal,user.createdAt,user.updatedAt,user.version,user.lastSavedAt,user.email,user.pin4,user.employeeId];if(row>0){sheet.getRange(row,1,1,values.length).setValues([values]);return{type:'updated',row,id:employeeId,user:publicUser(user)};}sheet.appendRow(values);return{type:'inserted',row:sheet.getLastRow(),id:employeeId,user:publicUser(user)};}
function loginUser(ss,data){const sheet=ss.getSheetByName(SHEET_USERS);const employeeId=normalizeEmployeeId(data.employeeId||data.id||'');const email=normalizeEmail(data.email||'');const pin4=normalizePin(data.pin4||'');if((!employeeId&&!email)||!pin4)return null;const users=readTable(sheet);const user=users.find(u=>{const sameEmployee=employeeId&&(normalizeEmployeeId(u.employeeId||u.id||'')===employeeId);const sameEmail=email&&(normalizeEmail(u.email||'')===email);return sameEmployee||sameEmail;});if(!user)return null;const storedPin=normalizePin(user.pin4||'');if(storedPin&&storedPin!==pin4)return null;if(!storedPin){const row=findRowByValue(sheet,1,normalizeEmployeeId(user.id||user.employeeId||employeeId));if(row>0){sheet.getRange(row,13).setNumberFormat('@').setValue(pin4);}user.pin4=pin4;}return publicUser(user);}
function saveActivity(ss,data){const sheet=ss.getSheetByName(SHEET_ACTIVITIES);const activityId=String(data.activityId||'').trim();if(!activityId)throw new Error('activity_id_required');const row=findRowByValue(sheet,1,activityId);const values=[activityId,data.participantId||data.id||'',data.deviceId||'',data.date||'',Number(data.steps||0),data.challenge===true||data.challenge==='true',data.comment||'',data.createdAt||'',data.version||data.appVersion||VERSION,new Date().toISOString()];if(row>0){sheet.getRange(row,1,1,values.length).setValues([values]);return{type:'updated',row,activityId};}sheet.appendRow(values);return{type:'inserted',row:sheet.getLastRow(),activityId};}
function deleteActivity(ss,data){const sheet=ss.getSheetByName(SHEET_ACTIVITIES);const activityId=String(data.activityId||'').trim();if(!activityId)throw new Error('activity_id_required');const row=findRowByValue(sheet,1,activityId);if(row>0){sheet.deleteRow(row);return{deleted:true,row,activityId};}return{deleted:false,row:-1,activityId};}
function saveThanks(ss,data){const sheet=ss.getSheetByName(SHEET_THANKS);const thanksId=String(data.thanksId||('K'+Date.now().toString(36))).trim();const row=findRowByValue(sheet,1,thanksId);const now=new Date().toISOString();const values=[thanksId,data.fromParticipantId||'',data.fromName||'',data.toParticipantId||'',data.toName||'',data.toDept||'',data.reason||'ありがとう',data.createdAt||now,data.version||data.appVersion||VERSION,now];if(row>0){sheet.getRange(row,1,1,values.length).setValues([values]);return{type:'updated',row,thanksId};}sheet.appendRow(values);return{type:'inserted',row:sheet.getLastRow(),thanksId};}
function getMyThanks(ss,data){const id=normalizeEmployeeId(data.employeeId||data.id||data.toParticipantId||'');if(!id)return[];return readTable(ss.getSheetByName(SHEET_THANKS)).filter(t=>normalizeEmployeeId(t.toParticipantId||'')===id).sort((a,b)=>String(b.createdAt||'').localeCompare(String(a.createdAt||''))).slice(0,50);}
function getDashboard(ss){const users=readTable(ss.getSheetByName(SHEET_USERS));const activities=readTable(ss.getSheetByName(SHEET_ACTIVITIES));const thanks=readTable(ss.getSheetByName(SHEET_THANKS));const byUser=buildUserStats(users,activities,true);const members=Object.keys(byUser).map(id=>byUser[id]);return{generatedAt:new Date().toISOString(),totalUsers:members.length,totalActivities:activities.length,totalSteps:activities.reduce((sum,item)=>sum+Number(item.steps||0),0),totalThanks:thanks.length,members,ranking:rankMembers(members).slice(0,20)};}
function getAdminStats(ss){const users=readTable(ss.getSheetByName(SHEET_USERS));const activities=readTable(ss.getSheetByName(SHEET_ACTIVITIES));const byUser=buildUserStats(users,activities,false);const members=Object.keys(byUser).map(id=>byUser[id]);const deptMap={},monthMap={},csvRows=[];activities.forEach(item=>{const user=byUser[item.participantId]||{};const dept=user.dept||'所属未設定';const date=String(item.date||'');const month=date.slice(0,7)||'日付未設定';const steps=Number(item.steps||0);if(!deptMap[dept])deptMap[dept]={dept,users:{},activityCount:0,totalSteps:0};deptMap[dept].users[item.participantId||'unknown']=true;deptMap[dept].activityCount+=1;deptMap[dept].totalSteps+=steps;if(!monthMap[month])monthMap[month]={month,activityCount:0,totalSteps:0};monthMap[month].activityCount+=1;monthMap[month].totalSteps+=steps;csvRows.push({date,activityId:item.activityId||'',participantId:item.participantId||'',name:user.name||'',nick:user.nick||'',dept,steps,challenge:item.challenge===true||item.challenge==='true',comment:item.comment||'',createdAt:item.createdAt||'',savedAt:item.savedAt||''});});const deptRanking=Object.keys(deptMap).map(k=>{const d=deptMap[k];return{dept:d.dept,userCount:Object.keys(d.users).length,activityCount:d.activityCount,totalSteps:d.totalSteps};}).sort((a,b)=>b.totalSteps-a.totalSteps);const monthly=Object.keys(monthMap).map(k=>monthMap[k]).sort((a,b)=>String(b.month).localeCompare(String(a.month)));return{generatedAt:new Date().toISOString(),totalUsers:members.length,totalActivities:activities.length,totalSteps:activities.reduce((sum,item)=>sum+Number(item.steps||0),0),ranking:rankMembers(members),deptRanking,monthly,csvRows};}
function buildUserStats(users,activities,masked){const byUser={};users.forEach(user=>{const id=normalizeEmployeeId(user.employeeId||user.id||'');if(!id)return;byUser[id]={id,employeeId:id,name:masked?maskName(user.name||''):(user.name||''),nick:user.nick||'',dept:user.dept||'',declaration:user.declaration||'',weeklyGoal:user.weeklyGoal||'',activityCount:0,totalSteps:0,lastDate:''};});activities.forEach(item=>{const id=normalizeEmployeeId(item.participantId||'');if(!id)return;if(!byUser[id])byUser[id]={id,employeeId:id,name:'ゲスト',nick:'',dept:'',declaration:'',weeklyGoal:'',activityCount:0,totalSteps:0,lastDate:''};byUser[id].activityCount+=1;byUser[id].totalSteps+=Number(item.steps||0);if(!byUser[id].lastDate||String(item.date||'')>byUser[id].lastDate)byUser[id].lastDate=String(item.date||'');});return byUser;}
function rankMembers(members){return members.slice().sort((a,b)=>b.totalSteps!==a.totalSteps?b.totalSteps-a.totalSteps:b.activityCount-a.activityCount);}
function rowToObject(sheet,row){const headers=sheet.getRange(1,1,1,sheet.getLastColumn()).getValues()[0].map(String);const values=sheet.getRange(row,1,1,sheet.getLastColumn()).getValues()[0];const obj={};headers.forEach((h,i)=>obj[h]=values[i]);return obj;}
function publicUser(user){return{id:normalizeEmployeeId(user.employeeId||user.id||''),employeeId:normalizeEmployeeId(user.employeeId||user.id||''),deviceId:user.deviceId||'',name:user.name||'',dept:user.dept||'',nick:user.nick||'',declaration:user.declaration||'',weeklyGoal:user.weeklyGoal||'',createdAt:user.createdAt||'',updatedAt:user.updatedAt||'',version:user.version||VERSION,email:user.email||''};}
function normalizeEmployeeId(value){return String(value||'').trim();}
function normalizeEmail(email){return String(email||'').trim().toLowerCase();}
function normalizePin(pin){const digits=String(pin||'').replace(/\D/g,'');if(!digits)return'';return digits.slice(-4).padStart(4,'0');}
function readTable(sheet){if(!sheet||sheet.getLastRow()<2)return[];const values=sheet.getDataRange().getValues();const headers=values.shift().map(String);return values.map(row=>{const obj={};headers.forEach((h,i)=>obj[h]=row[i]);return obj;});}
function maskName(name){const text=String(name||'').trim();if(!text)return'ゲスト';if(text.length<=2)return text;return text.slice(0,1)+'＊'+text.slice(-1);}
function findRowByValue(sheet,col,value){const lastRow=sheet.getLastRow();if(lastRow<2)return-1;const values=sheet.getRange(2,col,lastRow-1,1).getValues();for(let i=0;i<values.length;i++){if(String(values[i][0])===String(value))return i+2;}return-1;}
function writeLog(ss,action,deviceId,participantId,status,message){const sheet=ss.getSheetByName(SHEET_LOGS);sheet.appendRow([new Date().toISOString(),action||'',deviceId||'',participantId||'',status||'',message||'']);}
